import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const stocks = [
  // Bankacılık
  { symbol: 'GARAN', name: 'Garanti BBVA Bankası', sector: 'Bankacılık', basePrice: 128.40, yahooSymbol: 'GARAN.IS', marketCap: 540000000000 },
  { symbol: 'AKBNK', name: 'Akbank', sector: 'Bankacılık', basePrice: 62.85, yahooSymbol: 'AKBNK.IS', marketCap: 327000000000 },
  { symbol: 'ISCTR', name: 'İş Bankası C', sector: 'Bankacılık', basePrice: 14.56, yahooSymbol: 'ISCTR.IS', marketCap: 146000000000 },
  { symbol: 'YKBNK', name: 'Yapı Kredi Bankası', sector: 'Bankacılık', basePrice: 30.82, yahooSymbol: 'YKBNK.IS', marketCap: 259000000000 },
  { symbol: 'HALKB', name: 'Halkbank', sector: 'Bankacılık', basePrice: 19.46, yahooSymbol: 'HALKB.IS', marketCap: 97000000000 },
  { symbol: 'VAKBN', name: 'Vakıfbank', sector: 'Bankacılık', basePrice: 21.10, yahooSymbol: 'VAKBN.IS', marketCap: 105000000000 },
  { symbol: 'TSKB', name: 'TSKB', sector: 'Bankacılık', basePrice: 27.50, yahooSymbol: 'TSKB.IS', marketCap: 55000000000 },
  { symbol: 'SKBNK', name: 'Şekerbank', sector: 'Bankacılık', basePrice: 8.92, yahooSymbol: 'SKBNK.IS', marketCap: 11000000000 },
  { symbol: 'ALBRK', name: 'Albaraka Türk', sector: 'Bankacılık', basePrice: 5.61, yahooSymbol: 'ALBRK.IS', marketCap: 8000000000 },

  // Holding
  { symbol: 'KCHOL', name: 'Koç Holding', sector: 'Holding', basePrice: 188.60, yahooSymbol: 'KCHOL.IS', marketCap: 479000000000 },
  { symbol: 'SAHOL', name: 'Sabancı Holding', sector: 'Holding', basePrice: 82.45, yahooSymbol: 'SAHOL.IS', marketCap: 168000000000 },
  { symbol: 'DOHOL', name: 'Doğan Holding', sector: 'Holding', basePrice: 18.45, yahooSymbol: 'DOHOL.IS', marketCap: 46000000000 },
  { symbol: 'AGHOL', name: 'Anadolu Grubu Holding', sector: 'Holding', basePrice: 95.20, yahooSymbol: 'AGHOL.IS', marketCap: 60000000000 },
  { symbol: 'TAVHL', name: 'TAV Havalimanları', sector: 'Holding', basePrice: 98.80, yahooSymbol: 'TAVHL.IS', marketCap: 36000000000 },
  { symbol: 'ALARK', name: 'Alarko Holding', sector: 'Holding', basePrice: 72.50, yahooSymbol: 'ALARK.IS', marketCap: 14000000000 },
  { symbol: 'GLYHO', name: 'Global Yatırım Holding', sector: 'Holding', basePrice: 14.85, yahooSymbol: 'GLYHO.IS', marketCap: 8000000000 },

  // Ulaştırma & Havacılık
  { symbol: 'THYAO', name: 'Türk Hava Yolları', sector: 'Ulaştırma', basePrice: 292.50, yahooSymbol: 'THYAO.IS', marketCap: 403000000000 },
  { symbol: 'PGSUS', name: 'Pegasus Hava Yolları', sector: 'Ulaştırma', basePrice: 620.00, yahooSymbol: 'PGSUS.IS', marketCap: 63000000000 },
  { symbol: 'CLEBI', name: 'Çelebi Havacılık', sector: 'Ulaştırma', basePrice: 310.00, yahooSymbol: 'CLEBI.IS', marketCap: 7500000000 },

  // Enerji & Petrokimya
  { symbol: 'TUPRS', name: 'Tüpraş', sector: 'Enerji', basePrice: 172.80, yahooSymbol: 'TUPRS.IS', marketCap: 172000000000 },
  { symbol: 'AKSEN', name: 'Aksa Enerji', sector: 'Enerji', basePrice: 52.40, yahooSymbol: 'AKSEN.IS', marketCap: 32000000000 },
  { symbol: 'AYEN', name: 'Ayen Enerji', sector: 'Enerji', basePrice: 24.30, yahooSymbol: 'AYEN.IS', marketCap: 15000000000 },
  { symbol: 'ODAS', name: 'Odaş Elektrik', sector: 'Enerji', basePrice: 7.25, yahooSymbol: 'ODAS.IS', marketCap: 7000000000 },
  { symbol: 'GESAN', name: 'Girişim Elektrik', sector: 'Enerji', basePrice: 36.80, yahooSymbol: 'GESAN.IS', marketCap: 9000000000 },
  { symbol: 'KONTR', name: 'Kontrolmatik', sector: 'Enerji', basePrice: 84.20, yahooSymbol: 'KONTR.IS', marketCap: 12000000000 },
  { symbol: 'ASTOR', name: 'Astor Enerji', sector: 'Enerji', basePrice: 65.90, yahooSymbol: 'ASTOR.IS', marketCap: 15000000000 },

  // Telekomünikasyon
  { symbol: 'TCELL', name: 'Turkcell', sector: 'Telekomünikasyon', basePrice: 98.50, yahooSymbol: 'TCELL.IS', marketCap: 218000000000 },
  { symbol: 'TTKOM', name: 'Türk Telekom', sector: 'Telekomünikasyon', basePrice: 47.80, yahooSymbol: 'TTKOM.IS', marketCap: 167000000000 },

  // Metal & Madencilik
  { symbol: 'EREGL', name: 'Ereğli Demir Çelik', sector: 'Metal & Madencilik', basePrice: 53.75, yahooSymbol: 'EREGL.IS', marketCap: 189000000000 },
  { symbol: 'KRDMD', name: 'Kardemir D', sector: 'Metal & Madencilik', basePrice: 34.52, yahooSymbol: 'KRDMD.IS', marketCap: 27000000000 },

  // Cam & Kimya
  { symbol: 'SISE', name: 'Şişecam', sector: 'Cam & Kimya', basePrice: 54.30, yahooSymbol: 'SISE.IS', marketCap: 136000000000 },
  { symbol: 'PETKM', name: 'Petkim', sector: 'Kimya', basePrice: 25.48, yahooSymbol: 'PETKM.IS', marketCap: 51000000000 },
  { symbol: 'SASA', name: 'SASA Polyester', sector: 'Kimya', basePrice: 62.50, yahooSymbol: 'SASA.IS', marketCap: 56000000000 },
  { symbol: 'HEKTS', name: 'Hektaş', sector: 'Kimya', basePrice: 92.70, yahooSymbol: 'HEKTS.IS', marketCap: 27000000000 },
  { symbol: 'AKSA', name: 'Aksa Akrilik', sector: 'Kimya', basePrice: 52.80, yahooSymbol: 'AKSA.IS', marketCap: 18000000000 },
  { symbol: 'GUBRF', name: 'Gübre Fabrikaları', sector: 'Kimya', basePrice: 175.00, yahooSymbol: 'GUBRF.IS', marketCap: 32000000000 },
  { symbol: 'BRSAN', name: 'Borusan Mannesmann', sector: 'Metal & Madencilik', basePrice: 290.00, yahooSymbol: 'BRSAN.IS', marketCap: 12000000000 },

  // Otomotiv
  { symbol: 'TOASO', name: 'Tofaş Otomobil', sector: 'Otomotiv', basePrice: 228.40, yahooSymbol: 'TOASO.IS', marketCap: 114000000000 },
  { symbol: 'FROTO', name: 'Ford Otosan', sector: 'Otomotiv', basePrice: 1050.00, yahooSymbol: 'FROTO.IS', marketCap: 368000000000 },
  { symbol: 'OTKAR', name: 'Otokar', sector: 'Otomotiv', basePrice: 780.00, yahooSymbol: 'OTKAR.IS', marketCap: 19000000000 },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv', sector: 'Otomotiv', basePrice: 260.00, yahooSymbol: 'DOAS.IS', marketCap: 57000000000 },
  { symbol: 'TTRAK', name: 'Türk Traktör', sector: 'Otomotiv', basePrice: 1280.00, yahooSymbol: 'TTRAK.IS', marketCap: 66000000000 },

  // Perakende & Gıda
  { symbol: 'BIMAS', name: 'BİM Mağazalar', sector: 'Perakende', basePrice: 460.00, yahooSymbol: 'BIMAS.IS', marketCap: 279000000000 },
  { symbol: 'MGROS', name: 'Migros Ticaret', sector: 'Perakende', basePrice: 540.00, yahooSymbol: 'MGROS.IS', marketCap: 98000000000 },
  { symbol: 'SOKM', name: 'Şok Marketler', sector: 'Perakende', basePrice: 38.50, yahooSymbol: 'SOKM.IS', marketCap: 85000000000 },
  { symbol: 'CCOLA', name: 'Coca-Cola İçecek', sector: 'Gıda & İçecek', basePrice: 840.00, yahooSymbol: 'CCOLA.IS', marketCap: 213000000000 },
  { symbol: 'AEFES', name: 'Anadolu Efes', sector: 'Gıda & İçecek', basePrice: 370.00, yahooSymbol: 'AEFES.IS', marketCap: 220000000000 },
  { symbol: 'ULKER', name: 'Ülker Bisküvi', sector: 'Gıda & İçecek', basePrice: 165.00, yahooSymbol: 'ULKER.IS', marketCap: 56000000000 },
  { symbol: 'BANVT', name: 'Banvit', sector: 'Gıda & İçecek', basePrice: 56.80, yahooSymbol: 'BANVT.IS', marketCap: 7000000000 },
  { symbol: 'TATGD', name: 'Tat Gıda', sector: 'Gıda & İçecek', basePrice: 68.20, yahooSymbol: 'TATGD.IS', marketCap: 12000000000 },
  { symbol: 'PNSUT', name: 'Pınar Süt', sector: 'Gıda & İçecek', basePrice: 98.40, yahooSymbol: 'PNSUT.IS', marketCap: 5800000000 },

  // Savunma & Teknoloji
  { symbol: 'ASELS', name: 'Aselsan', sector: 'Savunma', basePrice: 67.80, yahooSymbol: 'ASELS.IS', marketCap: 135000000000 },
  { symbol: 'ALFAS', name: 'Alfa Solar Enerji', sector: 'Teknoloji', basePrice: 58.90, yahooSymbol: 'ALFAS.IS', marketCap: 12000000000 },
  { symbol: 'CANTE', name: 'Çan2 Termik', sector: 'Enerji', basePrice: 13.80, yahooSymbol: 'CANTE.IS', marketCap: 7000000000 },

  // Dayanıklı Tüketim
  { symbol: 'ARCLK', name: 'Arçelik', sector: 'Dayanıklı Tüketim', basePrice: 185.60, yahooSymbol: 'ARCLK.IS', marketCap: 125000000000 },
  { symbol: 'VESTL', name: 'Vestel Elektronik', sector: 'Dayanıklı Tüketim', basePrice: 38.90, yahooSymbol: 'VESTL.IS', marketCap: 13000000000 },
  { symbol: 'VESBE', name: 'Vestel Beyaz Eşya', sector: 'Dayanıklı Tüketim', basePrice: 115.00, yahooSymbol: 'VESBE.IS', marketCap: 22000000000 },

  // İnşaat & Gayrimenkul
  { symbol: 'ENKAI', name: 'Enka İnşaat', sector: 'İnşaat', basePrice: 42.60, yahooSymbol: 'ENKAI.IS', marketCap: 210000000000 },
  { symbol: 'EKGYO', name: 'Emlak Konut GYO', sector: 'GYO', basePrice: 12.95, yahooSymbol: 'EKGYO.IS', marketCap: 49000000000 },
  { symbol: 'ISGYO', name: 'İş GYO', sector: 'GYO', basePrice: 11.50, yahooSymbol: 'ISGYO.IS', marketCap: 31000000000 },
  { symbol: 'KLGYO', name: 'Kiler GYO', sector: 'GYO', basePrice: 6.80, yahooSymbol: 'KLGYO.IS', marketCap: 4000000000 },

  // Sigorta
  { symbol: 'ANHYT', name: 'Anadolu Hayat Emeklilik', sector: 'Sigorta', basePrice: 48.60, yahooSymbol: 'ANHYT.IS', marketCap: 14000000000 },
  { symbol: 'AGESA', name: 'Agesa Hayat Emeklilik', sector: 'Sigorta', basePrice: 62.30, yahooSymbol: 'AGESA.IS', marketCap: 11000000000 },
  { symbol: 'TURSG', name: 'Türkiye Sigorta', sector: 'Sigorta', basePrice: 22.40, yahooSymbol: 'TURSG.IS', marketCap: 13000000000 },

  // Demir Çelik & Sanayi
  { symbol: 'CEMTS', name: 'Çemtaş', sector: 'Metal & Madencilik', basePrice: 54.30, yahooSymbol: 'CEMTS.IS', marketCap: 5000000000 },
  { symbol: 'SARKY', name: 'Sarkuysan', sector: 'Metal & Madencilik', basePrice: 41.20, yahooSymbol: 'SARKY.IS', marketCap: 6000000000 },

  // Tekstil
  { symbol: 'MAVI', name: 'Mavi Giyim', sector: 'Tekstil', basePrice: 165.00, yahooSymbol: 'MAVI.IS', marketCap: 32000000000 },

  // Havacılık & Ulaşım
  { symbol: 'BERA', name: 'Bera Holding', sector: 'Holding', basePrice: 15.10, yahooSymbol: 'BERA.IS', marketCap: 7500000000 },
  { symbol: 'ENJSA', name: 'Enerjisa Enerji', sector: 'Enerji', basePrice: 42.50, yahooSymbol: 'ENJSA.IS', marketCap: 50000000000 },
  { symbol: 'EUPWR', name: 'Europower Enerji ve Otomasyon', sector: 'Enerji', basePrice: 28.60, yahooSymbol: 'EUPWR.IS', marketCap: 16000000000 },

  // Çimento & İnşaat
  { symbol: 'OYAKC', name: 'Oyak Çimento', sector: 'Çimento', basePrice: 48.90, yahooSymbol: 'OYAKC.IS', marketCap: 9000000000 },
  { symbol: 'BUCIM', name: 'Bursa Çimento', sector: 'Çimento', basePrice: 112.00, yahooSymbol: 'BUCIM.IS', marketCap: 7800000000 },
  { symbol: 'CIMSA', name: 'Çimsa Çimento', sector: 'Çimento', basePrice: 56.70, yahooSymbol: 'CIMSA.IS', marketCap: 8600000000 },

  // Finans & Aracı Kurum
  { symbol: 'ISMEN', name: 'İş Yatırım', sector: 'Finans', basePrice: 18.30, yahooSymbol: 'ISMEN.IS', marketCap: 12000000000 },
  { symbol: 'KAYSE', name: 'Kayseri Şeker', sector: 'Gıda & İçecek', basePrice: 58.40, yahooSymbol: 'KAYSE.IS', marketCap: 5500000000 },

  // Sağlık
  { symbol: 'MPARK', name: 'MLP Sağlık', sector: 'Sağlık', basePrice: 146.00, yahooSymbol: 'MPARK.IS', marketCap: 35000000000 },

  // Lojistik
  { symbol: 'BEYAZ', name: 'Beyaz Filo', sector: 'Ulaştırma', basePrice: 112.50, yahooSymbol: 'BEYAZ.IS', marketCap: 8500000000 },

  // Yazılım & Teknoloji
  { symbol: 'LOGO', name: 'Logo Yazılım', sector: 'Teknoloji', basePrice: 165.00, yahooSymbol: 'LOGO.IS', marketCap: 14000000000 },
  { symbol: 'NETAS', name: 'Netaş Telekomünikasyon', sector: 'Teknoloji', basePrice: 95.80, yahooSymbol: 'NETAS.IS', marketCap: 3900000000 },
  { symbol: 'ARENA', name: 'Arena Bilgisayar', sector: 'Teknoloji', basePrice: 68.50, yahooSymbol: 'ARENA.IS', marketCap: 4200000000 },
  { symbol: 'INDES', name: 'İndeks Bilgisayar', sector: 'Teknoloji', basePrice: 72.30, yahooSymbol: 'INDES.IS', marketCap: 5100000000 },

  // Seyahat & Turizm
  { symbol: 'KSTUR', name: 'Kuştur Kuşadası', sector: 'Turizm', basePrice: 48.60, yahooSymbol: 'KSTUR.IS', marketCap: 2500000000 },

  // Diğer Sanayi
  { symbol: 'KORDS', name: 'Kordsa', sector: 'Sanayi', basePrice: 108.50, yahooSymbol: 'KORDS.IS', marketCap: 21000000000 },
  { symbol: 'BTCIM', name: 'Batıçim', sector: 'Çimento', basePrice: 41.90, yahooSymbol: 'BTCIM.IS', marketCap: 5800000000 },
  { symbol: 'EGEEN', name: 'Ege Endüstri', sector: 'Otomotiv', basePrice: 1450.00, yahooSymbol: 'EGEEN.IS', marketCap: 10000000000 },
  { symbol: 'TMSN', name: 'Tümosan Motor', sector: 'Sanayi', basePrice: 32.80, yahooSymbol: 'TMSN.IS', marketCap: 4900000000 },
  { symbol: 'SMRTG', name: 'Smart Güneş Enerji', sector: 'Enerji', basePrice: 14.90, yahooSymbol: 'SMRTG.IS', marketCap: 6200000000 },
  { symbol: 'BAYRK', name: 'Bayrak Taban', sector: 'Sanayi', basePrice: 8.15, yahooSymbol: 'BAYRK.IS', marketCap: 2800000000 },
  { symbol: 'TKFEN', name: 'Tekfen Holding', sector: 'Holding', basePrice: 162.50, yahooSymbol: 'TKFEN.IS', marketCap: 60000000000 },
  { symbol: 'TUREX', name: 'Tureks Turunç', sector: 'Gıda & İçecek', basePrice: 21.60, yahooSymbol: 'TUREX.IS', marketCap: 3500000000 },
  { symbol: 'PRKME', name: 'Park Elektrik Madencilik', sector: 'Madencilik', basePrice: 24.80, yahooSymbol: 'PRKME.IS', marketCap: 7000000000 },
  { symbol: 'BINHO', name: '1000 Yatırımlar Holding', sector: 'Holding', basePrice: 9.55, yahooSymbol: 'BINHO.IS', marketCap: 3200000000 },
  { symbol: 'KARSN', name: 'Karsan Otomotiv', sector: 'Otomotiv', basePrice: 28.40, yahooSymbol: 'KARSN.IS', marketCap: 12000000000 },
  { symbol: 'TRGYO', name: 'Torunlar GYO', sector: 'GYO', basePrice: 8.20, yahooSymbol: 'TRGYO.IS', marketCap: 16000000000 },
  { symbol: 'PAPIL', name: 'Papilon Savunma', sector: 'Savunma', basePrice: 45.60, yahooSymbol: 'PAPIL.IS', marketCap: 7000000000 },

  // BIST 500 Ek Hisseler
  // Bankacılık (ek)
  { symbol: 'ICBCT', name: 'ICBC Turkey Bank', sector: 'Bankacılık', basePrice: 7.80, yahooSymbol: 'ICBCT.IS', marketCap: 3900000000 },
  { symbol: 'KLNMA', name: 'Kalkınma Yatırım', sector: 'Bankacılık', basePrice: 44.20, yahooSymbol: 'KLNMA.IS', marketCap: 5500000000 },
  // Sigorta
  { symbol: 'ANSGR', name: 'Anadolu Sigorta', sector: 'Sigorta', basePrice: 21.40, yahooSymbol: 'ANSGR.IS', marketCap: 5400000000 },
  { symbol: 'AKGRT', name: 'Aksigorta', sector: 'Sigorta', basePrice: 72.50, yahooSymbol: 'AKGRT.IS', marketCap: 7200000000 },
  { symbol: 'RAYSG', name: 'Ray Sigorta', sector: 'Sigorta', basePrice: 15.60, yahooSymbol: 'RAYSG.IS', marketCap: 1950000000 },
  { symbol: 'BNTAS', name: 'Bantaş Bandırma Ambalaj', sector: 'Sigorta', basePrice: 4.20, yahooSymbol: 'BNTAS.IS', marketCap: 420000000 },
  { symbol: 'EUKYO', name: 'Euro Kapital Yatırım Ortaklığı', sector: 'Sigorta', basePrice: 28.00, yahooSymbol: 'EUKYO.IS', marketCap: 2800000000 },
  // GYO (Gayrimenkul Yatırım)
  { symbol: 'HLGYO', name: 'Halk GYO', sector: 'GYO', basePrice: 5.82, yahooSymbol: 'HLGYO.IS', marketCap: 5800000000 },
  { symbol: 'VKGYO', name: 'Vakıf GYO', sector: 'GYO', basePrice: 9.15, yahooSymbol: 'VKGYO.IS', marketCap: 4600000000 },
  { symbol: 'YGGYO', name: 'Yeni Gimat GYO', sector: 'GYO', basePrice: 3.45, yahooSymbol: 'YGGYO.IS', marketCap: 2070000000 },
  { symbol: 'RYGYO', name: 'Reysaş GYO', sector: 'GYO', basePrice: 7.20, yahooSymbol: 'RYGYO.IS', marketCap: 2160000000 },
  { symbol: 'MSGYO', name: 'Mistral GYO', sector: 'GYO', basePrice: 2.80, yahooSymbol: 'MSGYO.IS', marketCap: 700000000 },
  { symbol: 'PAGYO', name: 'Panora GYO', sector: 'GYO', basePrice: 12.40, yahooSymbol: 'PAGYO.IS', marketCap: 1240000000 },
  { symbol: 'OZKGY', name: 'Özak GYO', sector: 'GYO', basePrice: 18.90, yahooSymbol: 'OZKGY.IS', marketCap: 3780000000 },
  { symbol: 'SNGYO', name: 'Sinpaş GYO', sector: 'GYO', basePrice: 4.10, yahooSymbol: 'SNGYO.IS', marketCap: 1230000000 },
  { symbol: 'DGGYO', name: 'Doğuş GYO', sector: 'GYO', basePrice: 6.30, yahooSymbol: 'DGGYO.IS', marketCap: 1260000000 },
  { symbol: 'KRGYO', name: 'Körfez GYO', sector: 'GYO', basePrice: 3.20, yahooSymbol: 'KRGYO.IS', marketCap: 640000000 },
  { symbol: 'DZGYO', name: 'Deniz GYO', sector: 'GYO', basePrice: 5.50, yahooSymbol: 'DZGYO.IS', marketCap: 1100000000 },
  { symbol: 'ALGYO', name: 'Alarko GYO', sector: 'GYO', basePrice: 24.60, yahooSymbol: 'ALGYO.IS', marketCap: 2460000000 },
  { symbol: 'NUGYO', name: 'Nurol GYO', sector: 'GYO', basePrice: 22.50, yahooSymbol: 'NUGYO.IS', marketCap: 2250000000 },
  { symbol: 'PEKGY', name: 'Peker GYO', sector: 'GYO', basePrice: 11.80, yahooSymbol: 'PEKGY.IS', marketCap: 1180000000 },
  { symbol: 'TDGYO', name: 'Trend GYO', sector: 'GYO', basePrice: 4.70, yahooSymbol: 'TDGYO.IS', marketCap: 470000000 },
  { symbol: 'AHSGY', name: 'Ahes GYO', sector: 'GYO', basePrice: 3.80, yahooSymbol: 'AHSGY.IS', marketCap: 380000000 },
  { symbol: 'AKFGY', name: 'Akfen GYO', sector: 'GYO', basePrice: 14.80, yahooSymbol: 'AKFGY.IS', marketCap: 1480000000 },
  { symbol: 'AKSGY', name: 'Akiş GYO', sector: 'GYO', basePrice: 9.20, yahooSymbol: 'AKSGY.IS', marketCap: 920000000 },
  { symbol: 'FZLGY', name: 'Fuzul GYO', sector: 'GYO', basePrice: 4.60, yahooSymbol: 'FZLGY.IS', marketCap: 460000000 },
  { symbol: 'OZGYO', name: 'Özderici GYO', sector: 'GYO', basePrice: 6.80, yahooSymbol: 'OZGYO.IS', marketCap: 680000000 },
  { symbol: 'VERUS', name: 'Verusaturk GYO', sector: 'GYO', basePrice: 7.40, yahooSymbol: 'VERUS.IS', marketCap: 740000000 },
  // Demir-Çelik & Metal
  { symbol: 'ISDMR', name: 'İskenderun Demir Çelik', sector: 'Metal', basePrice: 12.80, yahooSymbol: 'ISDMR.IS', marketCap: 32000000000 },
  { symbol: 'KRDMA', name: 'Kardemir A', sector: 'Metal', basePrice: 6.40, yahooSymbol: 'KRDMA.IS', marketCap: 6400000000 },
  { symbol: 'KRDMB', name: 'Kardemir B', sector: 'Metal', basePrice: 6.20, yahooSymbol: 'KRDMB.IS', marketCap: 6200000000 },
  { symbol: 'CELHA', name: 'Çelik Halat', sector: 'Metal', basePrice: 38.40, yahooSymbol: 'CELHA.IS', marketCap: 1920000000 },
  { symbol: 'IZMDC', name: 'İzmir Demir Çelik', sector: 'Metal', basePrice: 5.20, yahooSymbol: 'IZMDC.IS', marketCap: 1040000000 },
  { symbol: 'BURCE', name: 'Burçelik', sector: 'Metal', basePrice: 28.50, yahooSymbol: 'BURCE.IS', marketCap: 1425000000 },
  { symbol: 'DMSAS', name: 'Demisaş Döküm', sector: 'Metal', basePrice: 17.60, yahooSymbol: 'DMSAS.IS', marketCap: 880000000 },
  { symbol: 'FMIZP', name: 'F-M İzmir', sector: 'Metal', basePrice: 42.00, yahooSymbol: 'FMIZP.IS', marketCap: 2100000000 },
  { symbol: 'CUSAN', name: 'Çuhadaroğlu Metal', sector: 'Metal', basePrice: 22.40, yahooSymbol: 'CUSAN.IS', marketCap: 1120000000 },
  { symbol: 'FORMT', name: 'Formet Çelik', sector: 'Metal', basePrice: 22.40, yahooSymbol: 'FORMT.IS', marketCap: 1120000000 },
  { symbol: 'TUCLK', name: 'Tuğçelik Alüminyum', sector: 'Metal', basePrice: 16.00, yahooSymbol: 'TUCLK.IS', marketCap: 800000000 },
  { symbol: 'CEMZY', name: 'Cem Zeytin', sector: 'Metal', basePrice: 22.00, yahooSymbol: 'CEMZY.IS', marketCap: 1100000000 },
  // İnşaat & Altyapı
  { symbol: 'BRLSM', name: 'Birleşim Mühendislik', sector: 'İnşaat', basePrice: 52.00, yahooSymbol: 'BRLSM.IS', marketCap: 5200000000 },
  { symbol: 'KUYAS', name: 'Kuyaş Yatırım', sector: 'İnşaat', basePrice: 3.40, yahooSymbol: 'KUYAS.IS', marketCap: 680000000 },
  { symbol: 'ORCAY', name: 'Orçay Ortaköy', sector: 'İnşaat', basePrice: 5.80, yahooSymbol: 'ORCAY.IS', marketCap: 580000000 },
  { symbol: 'TURGG', name: 'Türker Proje', sector: 'İnşaat', basePrice: 6.40, yahooSymbol: 'TURGG.IS', marketCap: 640000000 },
  // Enerji (ek)
  { symbol: 'AKENR', name: 'Akenerji Elektrik', sector: 'Enerji', basePrice: 7.80, yahooSymbol: 'AKENR.IS', marketCap: 4680000000 },
  { symbol: 'ZOREN', name: 'Zorlu Enerji', sector: 'Enerji', basePrice: 4.52, yahooSymbol: 'ZOREN.IS', marketCap: 9040000000 },
  { symbol: 'AYDEM', name: 'Aydem Enerji', sector: 'Enerji', basePrice: 8.60, yahooSymbol: 'AYDEM.IS', marketCap: 8600000000 },
  { symbol: 'BIOEN', name: 'Biotrend Enerji', sector: 'Enerji', basePrice: 11.90, yahooSymbol: 'BIOEN.IS', marketCap: 2380000000 },
  { symbol: 'NATEN', name: 'Naturel Enerji', sector: 'Enerji', basePrice: 6.70, yahooSymbol: 'NATEN.IS', marketCap: 1340000000 },
  { symbol: 'HUNER', name: 'Hun Enerji', sector: 'Enerji', basePrice: 3.20, yahooSymbol: 'HUNER.IS', marketCap: 640000000 },
  { symbol: 'CWENE', name: 'CW Enerji', sector: 'Enerji', basePrice: 38.90, yahooSymbol: 'CWENE.IS', marketCap: 7780000000 },
  { symbol: 'CONSE', name: 'Consus Enerji', sector: 'Enerji', basePrice: 8.40, yahooSymbol: 'CONSE.IS', marketCap: 1680000000 },
  { symbol: 'AKFYE', name: 'Akfen Yenilenebilir', sector: 'Enerji', basePrice: 22.00, yahooSymbol: 'AKFYE.IS', marketCap: 4400000000 },
  { symbol: 'GWIND', name: 'Galata Wind Enerji', sector: 'Enerji', basePrice: 18.60, yahooSymbol: 'GWIND.IS', marketCap: 3720000000 },
  { symbol: 'DNISI', name: 'Dinamik ISI', sector: 'Enerji', basePrice: 7.40, yahooSymbol: 'DNISI.IS', marketCap: 740000000 },
  { symbol: 'IZENR', name: 'İzdemir Enerji', sector: 'Enerji', basePrice: 9.20, yahooSymbol: 'IZENR.IS', marketCap: 920000000 },
  { symbol: 'MANAS', name: 'Manas Enerji', sector: 'Enerji', basePrice: 6.20, yahooSymbol: 'MANAS.IS', marketCap: 620000000 },
  // Kimya & Plastik
  { symbol: 'DYOBY', name: 'DYO Boya', sector: 'Kimya', basePrice: 16.20, yahooSymbol: 'DYOBY.IS', marketCap: 3240000000 },
  { symbol: 'ALKIM', name: 'Alkim Kimya', sector: 'Kimya', basePrice: 42.50, yahooSymbol: 'ALKIM.IS', marketCap: 4250000000 },
  { symbol: 'BAGFS', name: 'Bagfaş Gübre', sector: 'Kimya', basePrice: 92.00, yahooSymbol: 'BAGFS.IS', marketCap: 4600000000 },
  { symbol: 'GOODY', name: 'Goodyear', sector: 'Kimya', basePrice: 280.00, yahooSymbol: 'GOODY.IS', marketCap: 5600000000 },
  { symbol: 'BRISA', name: 'Brisa Bridgestone', sector: 'Kimya', basePrice: 195.00, yahooSymbol: 'BRISA.IS', marketCap: 5850000000 },
  { symbol: 'MRSHL', name: 'Marshall Boya', sector: 'Kimya', basePrice: 65.00, yahooSymbol: 'MRSHL.IS', marketCap: 3250000000 },
  { symbol: 'POLTK', name: 'Politeknik Metal', sector: 'Kimya', basePrice: 18.40, yahooSymbol: 'POLTK.IS', marketCap: 920000000 },
  { symbol: 'TMPOL', name: 'Temapol Polimer', sector: 'Kimya', basePrice: 42.60, yahooSymbol: 'TMPOL.IS', marketCap: 2130000000 },
  { symbol: 'DOKTA', name: 'Döktaş Dökümcülük', sector: 'Kimya', basePrice: 14.80, yahooSymbol: 'DOKTA.IS', marketCap: 740000000 },
  { symbol: 'EGGUB', name: 'Ege Gübre', sector: 'Kimya', basePrice: 34.00, yahooSymbol: 'EGGUB.IS', marketCap: 3400000000 },
  { symbol: 'EPLAS', name: 'Egeplast', sector: 'Kimya', basePrice: 19.60, yahooSymbol: 'EPLAS.IS', marketCap: 980000000 },
  { symbol: 'MEGAP', name: 'Mega Polietilen', sector: 'Kimya', basePrice: 12.40, yahooSymbol: 'MEGAP.IS', marketCap: 1240000000 },
  { symbol: 'TEZOL', name: 'Europap Tezol Kağıt', sector: 'Kimya', basePrice: 4.60, yahooSymbol: 'TEZOL.IS', marketCap: 460000000 },
  // Tekstil & Giyim
  { symbol: 'DESA', name: 'Desa Deri', sector: 'Tekstil', basePrice: 38.50, yahooSymbol: 'DESA.IS', marketCap: 1925000000 },
  { symbol: 'YATAS', name: 'Yataş Yatak', sector: 'Tekstil', basePrice: 13.80, yahooSymbol: 'YATAS.IS', marketCap: 2760000000 },
  { symbol: 'HATEK', name: 'Hateks Hatay Tekstil', sector: 'Tekstil', basePrice: 10.60, yahooSymbol: 'HATEK.IS', marketCap: 530000000 },
  { symbol: 'LUKSK', name: 'Lüks Kadife', sector: 'Tekstil', basePrice: 22.00, yahooSymbol: 'LUKSK.IS', marketCap: 1100000000 },
  { symbol: 'BLCYT', name: 'Bilici Yatırım', sector: 'Tekstil', basePrice: 6.80, yahooSymbol: 'BLCYT.IS', marketCap: 680000000 },
  { symbol: 'DAGI', name: 'Dagi Giyim', sector: 'Tekstil', basePrice: 26.40, yahooSymbol: 'DAGI.IS', marketCap: 2640000000 },
  { symbol: 'BOSSA', name: 'Bossa Ticaret', sector: 'Tekstil', basePrice: 8.40, yahooSymbol: 'BOSSA.IS', marketCap: 1260000000 },
  { symbol: 'ARSAN', name: 'Arsan Tekstil', sector: 'Tekstil', basePrice: 11.20, yahooSymbol: 'ARSAN.IS', marketCap: 1120000000 },
  { symbol: 'SKTAS', name: 'Söktaş Tekstil', sector: 'Tekstil', basePrice: 16.90, yahooSymbol: 'SKTAS.IS', marketCap: 845000000 },
  { symbol: 'YUNSA', name: 'Yünsa Yünlü', sector: 'Tekstil', basePrice: 34.60, yahooSymbol: 'YUNSA.IS', marketCap: 1730000000 },
  { symbol: 'MNDRS', name: 'Menderes Tekstil', sector: 'Tekstil', basePrice: 7.90, yahooSymbol: 'MNDRS.IS', marketCap: 790000000 },
  { symbol: 'SONME', name: 'Sönmez Filament', sector: 'Tekstil', basePrice: 15.40, yahooSymbol: 'SONME.IS', marketCap: 770000000 },
  { symbol: 'RUBNS', name: 'Rubenis Tekstil', sector: 'Tekstil', basePrice: 8.40, yahooSymbol: 'RUBNS.IS', marketCap: 840000000 },
  { symbol: 'ALTNY', name: 'Altınay Savunma Teknolojileri', sector: 'Tekstil', basePrice: 15.20, yahooSymbol: 'ALTNY.IS', marketCap: 1520000000 },
  // Otomotiv & Yedek Parça (ek)
  { symbol: 'ASUZU', name: 'Anadolu Isuzu', sector: 'Otomotiv', basePrice: 185.00, yahooSymbol: 'ASUZU.IS', marketCap: 4625000000 },
  { symbol: 'PARSN', name: 'Parsan Makine', sector: 'Otomotiv', basePrice: 42.00, yahooSymbol: 'PARSN.IS', marketCap: 2100000000 },
  { symbol: 'KATMR', name: 'Katmerciler Araç', sector: 'Otomotiv', basePrice: 34.80, yahooSymbol: 'KATMR.IS', marketCap: 3480000000 },
  { symbol: 'DITAS', name: 'Ditaş Doğan Yedek', sector: 'Otomotiv', basePrice: 38.00, yahooSymbol: 'DITAS.IS', marketCap: 1900000000 },
  // Gıda & İçecek (ek)
  { symbol: 'AVOD', name: 'A.V.O.D. Gıda', sector: 'Gıda', basePrice: 5.20, yahooSymbol: 'AVOD.IS', marketCap: 520000000 },
  { symbol: 'ERSU', name: 'Ersu Meyve', sector: 'Gıda', basePrice: 12.40, yahooSymbol: 'ERSU.IS', marketCap: 620000000 },
  { symbol: 'FADE', name: 'Fade Gıda', sector: 'Gıda', basePrice: 8.90, yahooSymbol: 'FADE.IS', marketCap: 890000000 },
  { symbol: 'KENT', name: 'Kent Gıda', sector: 'Gıda', basePrice: 195.00, yahooSymbol: 'KENT.IS', marketCap: 3900000000 },
  { symbol: 'KNFRT', name: 'Konfrut Gıda', sector: 'Gıda', basePrice: 85.00, yahooSymbol: 'KNFRT.IS', marketCap: 2550000000 },
  { symbol: 'KERVN', name: 'Kervan Gıda', sector: 'Gıda', basePrice: 95.50, yahooSymbol: 'KERVN.IS', marketCap: 4775000000 },
  { symbol: 'MERKO', name: 'Merko Gıda', sector: 'Gıda', basePrice: 6.10, yahooSymbol: 'MERKO.IS', marketCap: 610000000 },
  { symbol: 'PENGD', name: 'Penguen Gıda', sector: 'Gıda', basePrice: 7.30, yahooSymbol: 'PENGD.IS', marketCap: 730000000 },
  { symbol: 'PINSU', name: 'Pınar Su', sector: 'Gıda', basePrice: 18.90, yahooSymbol: 'PINSU.IS', marketCap: 1890000000 },
  { symbol: 'TBORG', name: 'T.Tuborg Bira', sector: 'Gıda', basePrice: 78.00, yahooSymbol: 'TBORG.IS', marketCap: 3900000000 },
  { symbol: 'ULUUN', name: 'Ulusoy Un', sector: 'Gıda', basePrice: 25.80, yahooSymbol: 'ULUUN.IS', marketCap: 1290000000 },
  { symbol: 'DARDL', name: 'Dardanel Gıda', sector: 'Gıda', basePrice: 6.90, yahooSymbol: 'DARDL.IS', marketCap: 1380000000 },
  { symbol: 'SELVA', name: 'Selva Gıda', sector: 'Gıda', basePrice: 26.80, yahooSymbol: 'SELVA.IS', marketCap: 2680000000 },
  { symbol: 'YYLGD', name: 'Yayla Gıda', sector: 'Gıda', basePrice: 32.00, yahooSymbol: 'YYLGD.IS', marketCap: 3200000000 },
  { symbol: 'KTSKR', name: 'Kütahya Şeker', sector: 'Gıda', basePrice: 18.60, yahooSymbol: 'KTSKR.IS', marketCap: 1860000000 },
  { symbol: 'FRIGO', name: 'Frigo-Pak Gıda', sector: 'Gıda', basePrice: 18.60, yahooSymbol: 'FRIGO.IS', marketCap: 930000000 },
  // Teknoloji & Yazılım (ek)
  { symbol: 'ARDYZ', name: 'Ard Grup Bilişim', sector: 'Teknoloji', basePrice: 12.60, yahooSymbol: 'ARDYZ.IS', marketCap: 1260000000 },
  { symbol: 'ESCOM', name: 'Escort Teknoloji', sector: 'Teknoloji', basePrice: 22.40, yahooSymbol: 'ESCOM.IS', marketCap: 2240000000 },
  { symbol: 'FONET', name: 'Fonet Bilgi Teknoloji', sector: 'Teknoloji', basePrice: 16.50, yahooSymbol: 'FONET.IS', marketCap: 1650000000 },
  { symbol: 'HTTBT', name: 'Hitit Bilgisayar', sector: 'Teknoloji', basePrice: 120.00, yahooSymbol: 'HTTBT.IS', marketCap: 3600000000 },
  { symbol: 'KFEIN', name: 'Kafein Yazılım', sector: 'Teknoloji', basePrice: 92.00, yahooSymbol: 'KFEIN.IS', marketCap: 4600000000 },
  { symbol: 'LINK', name: 'Link Bilgisayar', sector: 'Teknoloji', basePrice: 8.40, yahooSymbol: 'LINK.IS', marketCap: 840000000 },
  { symbol: 'NTHOL', name: 'Net Holding', sector: 'Teknoloji', basePrice: 32.60, yahooSymbol: 'NTHOL.IS', marketCap: 3260000000 },
  { symbol: 'PKART', name: 'Plastikkart', sector: 'Teknoloji', basePrice: 34.20, yahooSymbol: 'PKART.IS', marketCap: 1710000000 },
  { symbol: 'SMART', name: 'Smartiks Yazılım', sector: 'Teknoloji', basePrice: 18.90, yahooSymbol: 'SMART.IS', marketCap: 945000000 },
  { symbol: 'VBTYZ', name: 'VBT Yazılım', sector: 'Teknoloji', basePrice: 52.00, yahooSymbol: 'VBTYZ.IS', marketCap: 2600000000 },
  { symbol: 'DESPC', name: 'Despec Bilgisayar', sector: 'Teknoloji', basePrice: 36.40, yahooSymbol: 'DESPC.IS', marketCap: 1820000000 },
  { symbol: 'KRONT', name: 'Kron Telekomünikasyon', sector: 'Teknoloji', basePrice: 23.40, yahooSymbol: 'KRONT.IS', marketCap: 2340000000 },
  { symbol: 'BVSAN', name: 'Bulbuloğlu Vinç', sector: 'Teknoloji', basePrice: 7.60, yahooSymbol: 'BVSAN.IS', marketCap: 760000000 },
  { symbol: 'HUBVC', name: 'Hub Girişim', sector: 'Teknoloji', basePrice: 19.80, yahooSymbol: 'HUBVC.IS', marketCap: 1980000000 },
  { symbol: 'EDATA', name: 'E-Data Teknoloji', sector: 'Teknoloji', basePrice: 3.80, yahooSymbol: 'EDATA.IS', marketCap: 380000000 },
  { symbol: 'MAKTK', name: 'Makina Takım Endüstrisi', sector: 'Teknoloji', basePrice: 8.60, yahooSymbol: 'MAKTK.IS', marketCap: 860000000 },
  { symbol: 'INGRM', name: 'İngram Mikro', sector: 'Teknoloji', basePrice: 42.00, yahooSymbol: 'INGRM.IS', marketCap: 2100000000 },
  { symbol: 'OBASE', name: 'Obase Bilgisayar', sector: 'Teknoloji', basePrice: 9.20, yahooSymbol: 'OBASE.IS', marketCap: 460000000 },
  { symbol: 'PCILT', name: 'PC İletişim', sector: 'Teknoloji', basePrice: 4.80, yahooSymbol: 'PCILT.IS', marketCap: 480000000 },
  // Telekom
  { symbol: 'KAREL', name: 'Karel Elektronik', sector: 'Telekom', basePrice: 15.80, yahooSymbol: 'KAREL.IS', marketCap: 1580000000 },
  // Madencilik
  { symbol: 'LIDFA', name: 'Lider Faktoring', sector: 'Madencilik', basePrice: 5.80, yahooSymbol: 'LIDFA.IS', marketCap: 580000000 },
  { symbol: 'CVKMD', name: 'CVK Maden', sector: 'Madencilik', basePrice: 16.20, yahooSymbol: 'CVKMD.IS', marketCap: 1620000000 },
  // Cam & Seramik
  { symbol: 'EGSER', name: 'Ege Seramik', sector: 'Cam', basePrice: 10.40, yahooSymbol: 'EGSER.IS', marketCap: 1040000000 },
  { symbol: 'KUTPO', name: 'Kütahya Porselen', sector: 'Cam', basePrice: 14.20, yahooSymbol: 'KUTPO.IS', marketCap: 1420000000 },
  { symbol: 'USAK', name: 'Uşak Seramik', sector: 'Cam', basePrice: 6.80, yahooSymbol: 'USAK.IS', marketCap: 680000000 },
  { symbol: 'KLSER', name: 'Kaleseramik', sector: 'Cam', basePrice: 5.20, yahooSymbol: 'KLSER.IS', marketCap: 1040000000 },
  { symbol: 'QUAGR', name: 'QUA Granite', sector: 'Cam', basePrice: 6.80, yahooSymbol: 'QUAGR.IS', marketCap: 1360000000 },
  // Kağıt & Ambalaj
  { symbol: 'DURDO', name: 'Duran Doğan Basım', sector: 'Kağıt', basePrice: 8.90, yahooSymbol: 'DURDO.IS', marketCap: 445000000 },
  { symbol: 'VKING', name: 'Viking Kağıt', sector: 'Kağıt', basePrice: 22.00, yahooSymbol: 'VKING.IS', marketCap: 1100000000 },
  { symbol: 'BAKAB', name: 'Bak Ambalaj', sector: 'Kağıt', basePrice: 16.50, yahooSymbol: 'BAKAB.IS', marketCap: 825000000 },
  { symbol: 'KARTN', name: 'Kartonsan', sector: 'Kağıt', basePrice: 350.00, yahooSymbol: 'KARTN.IS', marketCap: 3500000000 },
  // Sağlık & İlaç
  { symbol: 'ECILC', name: 'Eczacıbaşı İlaç', sector: 'Sağlık', basePrice: 6.70, yahooSymbol: 'ECILC.IS', marketCap: 8040000000 },
  { symbol: 'SELEC', name: 'Selçuk Ecza', sector: 'Sağlık', basePrice: 72.00, yahooSymbol: 'SELEC.IS', marketCap: 7200000000 },
  { symbol: 'DEVA', name: 'Deva Holding', sector: 'Sağlık', basePrice: 36.40, yahooSymbol: 'DEVA.IS', marketCap: 7280000000 },
  { symbol: 'LKMNH', name: 'Lokman Hekim', sector: 'Sağlık', basePrice: 14.20, yahooSymbol: 'LKMNH.IS', marketCap: 1420000000 },
  { symbol: 'MEDTR', name: 'Meditera Tıbbi', sector: 'Sağlık', basePrice: 42.00, yahooSymbol: 'MEDTR.IS', marketCap: 2100000000 },
  { symbol: 'ONCSM', name: 'Oncosem Onkoloji', sector: 'Sağlık', basePrice: 16.40, yahooSymbol: 'ONCSM.IS', marketCap: 1640000000 },
  // Savunma (ek)
  { symbol: 'RTALB', name: 'RTA Laboratuvar', sector: 'Savunma', basePrice: 42.80, yahooSymbol: 'RTALB.IS', marketCap: 2140000000 },
  // Lojistik & Taşımacılık
  { symbol: 'RYSAS', name: 'Reysaş Taşımacılık', sector: 'Lojistik', basePrice: 12.80, yahooSymbol: 'RYSAS.IS', marketCap: 2560000000 },
  { symbol: 'DOCO', name: 'Do&Co Catering', sector: 'Lojistik', basePrice: 520.00, yahooSymbol: 'DOCO.IS', marketCap: 15600000000 },
  { symbol: 'GRSEL', name: 'Gür-Sel Turizm', sector: 'Lojistik', basePrice: 8.80, yahooSymbol: 'GRSEL.IS', marketCap: 880000000 },
  // Medya
  { symbol: 'HURGZ', name: 'Hürriyet Gazetecilik', sector: 'Medya', basePrice: 6.40, yahooSymbol: 'HURGZ.IS', marketCap: 1280000000 },
  { symbol: 'IHEVA', name: 'İhlas Ev Aletleri', sector: 'Medya', basePrice: 3.80, yahooSymbol: 'IHEVA.IS', marketCap: 760000000 },
  { symbol: 'CEOEM', name: 'CEO Event', sector: 'Medya', basePrice: 6.80, yahooSymbol: 'CEOEM.IS', marketCap: 680000000 },
  // Turizm & Otel
  { symbol: 'MAALT', name: 'Marmaris Altınyunus', sector: 'Turizm', basePrice: 94.00, yahooSymbol: 'MAALT.IS', marketCap: 4700000000 },
  { symbol: 'MERIT', name: 'Merit Turizm', sector: 'Turizm', basePrice: 18.40, yahooSymbol: 'MERIT.IS', marketCap: 920000000 },
  { symbol: 'MARTI', name: 'Martı Otel', sector: 'Turizm', basePrice: 4.60, yahooSymbol: 'MARTI.IS', marketCap: 920000000 },
  { symbol: 'PLTUR', name: 'Platform Turizm', sector: 'Turizm', basePrice: 7.20, yahooSymbol: 'PLTUR.IS', marketCap: 720000000 },
  { symbol: 'SUMAS', name: 'Sumas Suni Tahta ve Mobilya', sector: 'Turizm', basePrice: 24.00, yahooSymbol: 'SUMAS.IS', marketCap: 1200000000 },
  // Elektronik & Endüstriyel
  { symbol: 'SILVR', name: 'Silverline Endüstri', sector: 'Elektronik', basePrice: 18.60, yahooSymbol: 'SILVR.IS', marketCap: 930000000 },
  { symbol: 'PRKAB', name: 'Türk Prysmian Kablo', sector: 'Elektronik', basePrice: 92.00, yahooSymbol: 'PRKAB.IS', marketCap: 9200000000 },
  { symbol: 'KLMSN', name: 'Klimasan Klima', sector: 'Elektronik', basePrice: 78.00, yahooSymbol: 'KLMSN.IS', marketCap: 1560000000 },
  { symbol: 'EMKEL', name: 'Emek Elektrik', sector: 'Elektronik', basePrice: 13.40, yahooSymbol: 'EMKEL.IS', marketCap: 670000000 },
  { symbol: 'SANFM', name: 'Sanifoam', sector: 'Elektronik', basePrice: 31.00, yahooSymbol: 'SANFM.IS', marketCap: 1550000000 },
  // Çimento (ek)
  { symbol: 'AFYON', name: 'Afyon Çimento', sector: 'Çimento', basePrice: 12.40, yahooSymbol: 'AFYON.IS', marketCap: 1240000000 },
  { symbol: 'GOLTS', name: 'Göltaş Çimento', sector: 'Çimento', basePrice: 82.00, yahooSymbol: 'GOLTS.IS', marketCap: 4100000000 },
  { symbol: 'KONYA', name: 'Konya Çimento', sector: 'Çimento', basePrice: 112.00, yahooSymbol: 'KONYA.IS', marketCap: 5600000000 },
  { symbol: 'NUHCM', name: 'Nuh Çimento', sector: 'Çimento', basePrice: 28.40, yahooSymbol: 'NUHCM.IS', marketCap: 5680000000 },
  { symbol: 'AKCNS', name: 'Akçansa Çimento', sector: 'Çimento', basePrice: 62.00, yahooSymbol: 'AKCNS.IS', marketCap: 11780000000 },
  { symbol: 'CMBTN', name: 'Çimbeton', sector: 'Çimento', basePrice: 8.40, yahooSymbol: 'CMBTN.IS', marketCap: 840000000 },
  // Petrol & Gaz
  { symbol: 'AYGAZ', name: 'Aygaz', sector: 'Petrol', basePrice: 78.00, yahooSymbol: 'AYGAZ.IS', marketCap: 23400000000 },
  { symbol: 'EGEPO', name: 'Nasmed Özel Sağlık', sector: 'Petrol', basePrice: 24.80, yahooSymbol: 'EGEPO.IS', marketCap: 1240000000 },
  // Finans & Yatırım
  { symbol: 'INFO', name: 'Info Yatırım', sector: 'Finans', basePrice: 11.20, yahooSymbol: 'INFO.IS', marketCap: 1120000000 },
  { symbol: 'GLBMD', name: 'Global MD', sector: 'Finans', basePrice: 9.80, yahooSymbol: 'GLBMD.IS', marketCap: 980000000 },
  { symbol: 'GEDIK', name: 'Gedik Yatırım', sector: 'Finans', basePrice: 7.40, yahooSymbol: 'GEDIK.IS', marketCap: 740000000 },
  { symbol: 'ATAGY', name: 'Ata Yatırım', sector: 'Finans', basePrice: 13.60, yahooSymbol: 'ATAGY.IS', marketCap: 1360000000 },
  { symbol: 'FENER', name: 'Fenerbahçe Futbol', sector: 'Finans', basePrice: 78.00, yahooSymbol: 'FENER.IS', marketCap: 3900000000 },
  { symbol: 'GSRAY', name: 'Galatasaray Sportif', sector: 'Finans', basePrice: 42.00, yahooSymbol: 'GSRAY.IS', marketCap: 4200000000 },
  { symbol: 'BJKAS', name: 'Beşiktaş Futbol', sector: 'Finans', basePrice: 22.40, yahooSymbol: 'BJKAS.IS', marketCap: 1120000000 },
  { symbol: 'TSPOR', name: 'Trabzonspor Sportif', sector: 'Finans', basePrice: 8.90, yahooSymbol: 'TSPOR.IS', marketCap: 445000000 },
  { symbol: 'CASA', name: 'Casa Emtia', sector: 'Finans', basePrice: 4.20, yahooSymbol: 'CASA.IS', marketCap: 420000000 },
  { symbol: 'DENGE', name: 'Denge Yatırım', sector: 'Finans', basePrice: 5.80, yahooSymbol: 'DENGE.IS', marketCap: 580000000 },
  { symbol: 'EUYO', name: 'Euro Yatırım', sector: 'Finans', basePrice: 4.60, yahooSymbol: 'EUYO.IS', marketCap: 460000000 },
  { symbol: 'VAKFN', name: 'Vakıf Finans', sector: 'Finans', basePrice: 14.80, yahooSymbol: 'VAKFN.IS', marketCap: 1480000000 },
  // Faktoring & Leasing
  { symbol: 'GARFA', name: 'Garanti Faktoring', sector: 'Faktoring', basePrice: 28.00, yahooSymbol: 'GARFA.IS', marketCap: 1400000000 },
  // Holding (ek)
  { symbol: 'AVHOL', name: 'Avrupa Yatırım Holding', sector: 'Holding', basePrice: 12.00, yahooSymbol: 'AVHOL.IS', marketCap: 1200000000 },
  { symbol: 'GSDHO', name: 'GSD Holding', sector: 'Holding', basePrice: 7.60, yahooSymbol: 'GSDHO.IS', marketCap: 760000000 },
  { symbol: 'DERHL', name: 'Derlüks Yatırım Holding', sector: 'Holding', basePrice: 9.40, yahooSymbol: 'DERHL.IS', marketCap: 940000000 },
  { symbol: 'UMPAS', name: 'Umpaş Holding', sector: 'Holding', basePrice: 3.20, yahooSymbol: 'UMPAS.IS', marketCap: 320000000 },
  // Perakende
  { symbol: 'VAKKO', name: 'Vakko Tekstil', sector: 'Perakende', basePrice: 22.00, yahooSymbol: 'VAKKO.IS', marketCap: 2200000000 },
  { symbol: 'BIZIM', name: 'Bizim Toptan', sector: 'Perakende', basePrice: 62.00, yahooSymbol: 'BIZIM.IS', marketCap: 3100000000 },
  { symbol: 'TKNSA', name: 'Teknosa İç Dış', sector: 'Perakende', basePrice: 14.60, yahooSymbol: 'TKNSA.IS', marketCap: 1460000000 },
  { symbol: 'INTEM', name: 'İntema İnşaat ve Tesisat', sector: 'Perakende', basePrice: 32.00, yahooSymbol: 'INTEM.IS', marketCap: 1600000000 },
  // Mobilya
  { symbol: 'ORMA', name: 'Orma Orman Mahsulleri', sector: 'Mobilya', basePrice: 12.60, yahooSymbol: 'ORMA.IS', marketCap: 630000000 },
  { symbol: 'GENTS', name: 'Gentaş Dekorasyon', sector: 'Mobilya', basePrice: 16.40, yahooSymbol: 'GENTS.IS', marketCap: 820000000 },
  { symbol: 'YBTAS', name: 'Yibitaş Yozgat İnşaat Malzemeleri', sector: 'Mobilya', basePrice: 14.00, yahooSymbol: 'YBTAS.IS', marketCap: 1400000000 },
  // Tarım
  // Diğer
  { symbol: 'ACSEL', name: 'Acıselsan Acıpayam', sector: 'Diğer', basePrice: 72.00, yahooSymbol: 'ACSEL.IS', marketCap: 1440000000 },
  { symbol: 'BURVA', name: 'Burçelik Vana', sector: 'Diğer', basePrice: 14.60, yahooSymbol: 'BURVA.IS', marketCap: 730000000 },
  { symbol: 'EKIZ', name: 'Ekiz Kimya', sector: 'Diğer', basePrice: 7.80, yahooSymbol: 'EKIZ.IS', marketCap: 390000000 },
  { symbol: 'EMNIS', name: 'Eminiş Ambalaj', sector: 'Diğer', basePrice: 42.00, yahooSymbol: 'EMNIS.IS', marketCap: 2100000000 },
  { symbol: 'IZFAS', name: 'İzmir Fırça Sanayi', sector: 'Diğer', basePrice: 24.00, yahooSymbol: 'IZFAS.IS', marketCap: 1200000000 },
  { symbol: 'JANTS', name: 'Jantsa Jant', sector: 'Diğer', basePrice: 32.00, yahooSymbol: 'JANTS.IS', marketCap: 1600000000 },
  { symbol: 'ROYAL', name: 'Royal Halı', sector: 'Diğer', basePrice: 4.80, yahooSymbol: 'ROYAL.IS', marketCap: 960000000 },
  { symbol: 'OSTIM', name: 'Ostim Endüstriyel', sector: 'Diğer', basePrice: 38.00, yahooSymbol: 'OSTIM.IS', marketCap: 3800000000 },
  { symbol: 'PRZMA', name: 'Prizma Pres', sector: 'Diğer', basePrice: 18.40, yahooSymbol: 'PRZMA.IS', marketCap: 920000000 },
  { symbol: 'PSDTC', name: 'Pergamon Status Dış Ticaret', sector: 'Diğer', basePrice: 15.60, yahooSymbol: 'PSDTC.IS', marketCap: 780000000 },
  { symbol: 'TLMAN', name: 'Trabzon Liman İşletmeciliği', sector: 'Diğer', basePrice: 28.00, yahooSymbol: 'TLMAN.IS', marketCap: 1400000000 },
  { symbol: 'NTGAZ', name: 'Naturelgaz', sector: 'Diğer', basePrice: 6.40, yahooSymbol: 'NTGAZ.IS', marketCap: 640000000 },
  { symbol: 'NIBAS', name: 'Niğbaş Niğde', sector: 'Diğer', basePrice: 22.80, yahooSymbol: 'NIBAS.IS', marketCap: 1140000000 },
  { symbol: 'DAPGM', name: 'DAP Gayrimenkul', sector: 'Diğer', basePrice: 7.20, yahooSymbol: 'DAPGM.IS', marketCap: 720000000 },
  { symbol: 'ULUSE', name: 'Ulusoy Elektrik', sector: 'Diğer', basePrice: 15.40, yahooSymbol: 'ULUSE.IS', marketCap: 770000000 },
  { symbol: 'SAYAS', name: 'Say Yenilenebilir', sector: 'Diğer', basePrice: 9.60, yahooSymbol: 'SAYAS.IS', marketCap: 960000000 },
  { symbol: 'AHGAZ', name: 'Ahlatçı Doğalgaz', sector: 'Diğer', basePrice: 12.80, yahooSymbol: 'AHGAZ.IS', marketCap: 1280000000 },
  { symbol: 'ISBIR', name: 'İşbir Holding', sector: 'Diğer', basePrice: 420.00, yahooSymbol: 'ISBIR.IS', marketCap: 4200000000 },
  // Ek BİST hisseleri - popüler ve eksik olanlar
  { symbol: 'KTLEV', name: 'Katılım Evim Tasarruf Finansman', sector: 'Finans', basePrice: 83.00, yahooSymbol: 'KTLEV.IS', marketCap: 8300000000 },
  { symbol: 'MIATK', name: 'Mia Teknoloji', sector: 'Teknoloji', basePrice: 45.00, yahooSymbol: 'MIATK.IS', marketCap: 2250000000 },
  { symbol: 'OSMEN', name: 'Osmanlı Menkul Değerler', sector: 'Enerji', basePrice: 7.50, yahooSymbol: 'OSMEN.IS', marketCap: 750000000 },
  { symbol: 'SAMAT', name: 'Saray Matbaacılık', sector: 'Diğer', basePrice: 12.00, yahooSymbol: 'SAMAT.IS', marketCap: 600000000 },
  { symbol: 'EBEBK', name: 'Ebebek Mağazacılık', sector: 'Perakende', basePrice: 72.00, yahooSymbol: 'EBEBK.IS', marketCap: 7200000000 },
  { symbol: 'AYCES', name: 'Altınyunus Çeşme', sector: 'Turizm', basePrice: 11.00, yahooSymbol: 'AYCES.IS', marketCap: 550000000 },
  { symbol: 'ALCTL', name: 'Alcatel Lucent Teletaş', sector: 'Teknoloji', basePrice: 15.00, yahooSymbol: 'ALCTL.IS', marketCap: 750000000 },
  { symbol: 'ISSEN', name: 'İşbir Sentetik', sector: 'Sertifika', basePrice: 8.50, yahooSymbol: 'ISSEN.IS', marketCap: 850000000 },
  { symbol: 'ORGE', name: 'Orge Enerji', sector: 'Enerji', basePrice: 28.00, yahooSymbol: 'ORGE.IS', marketCap: 1400000000 },
  { symbol: 'YAYLA', name: 'Yayla Agro Gıda', sector: 'Gıda', basePrice: 32.00, yahooSymbol: 'YAYLA.IS', marketCap: 1600000000 },
  { symbol: 'RALYH', name: 'Ral Yatırım Holding', sector: 'Holding', basePrice: 2.80, yahooSymbol: 'RALYH.IS', marketCap: 280000000 },
  { symbol: 'TUKAS', name: 'Tukaş Gıda', sector: 'Gıda', basePrice: 7.80, yahooSymbol: 'TUKAS.IS', marketCap: 780000000 },
  { symbol: 'BRMEN', name: 'Birlik Mensucat', sector: 'Tekstil', basePrice: 10.50, yahooSymbol: 'BRMEN.IS', marketCap: 525000000 },
  { symbol: 'BOBET', name: 'Boğaziçi Beton', sector: 'İnşaat', basePrice: 6.20, yahooSymbol: 'BOBET.IS', marketCap: 310000000 },
  { symbol: 'MTRYO', name: 'Metro Yatırım Ortaklığı', sector: 'Finans', basePrice: 5.00, yahooSymbol: 'MTRYO.IS', marketCap: 500000000 },
  { symbol: 'YKSLN', name: 'Yükselen Çelik', sector: 'İnşaat', basePrice: 7.80, yahooSymbol: 'YKSLN.IS', marketCap: 780000000 },
  { symbol: 'BALAT', name: 'Balatacilar Balatacilik', sector: 'Otomotiv', basePrice: 44.00, yahooSymbol: 'BALAT.IS', marketCap: 2200000000 },
  { symbol: 'MAGEN', name: 'Margün Enerji', sector: 'Enerji', basePrice: 42.00, yahooSymbol: 'MAGEN.IS', marketCap: 4200000000 },
  // Sertifikalar
  { symbol: 'GLDTR', name: 'ICBC Altın Sertifikası', sector: 'Sertifika', basePrice: 120.00, yahooSymbol: 'GLDTR.IS', marketCap: 1200000000 },
  { symbol: 'GMSTR', name: 'ICBC Gümüş Sertifikası', sector: 'Sertifika', basePrice: 25.00, yahooSymbol: 'GMSTR.IS', marketCap: 500000000 },
  // Fonlar (Borsa Yatırım Fonları - ETF)
  { symbol: 'DJIST', name: 'İş Portföy BIST 30 ETF', sector: 'Fon', basePrice: 12.50, yahooSymbol: 'DJIST.IS', marketCap: 2500000000 },
  { symbol: 'A1CAP', name: 'A1 Capital Yatırım', sector: 'Finans', basePrice: 30.00, yahooSymbol: 'A1CAP.IS', marketCap: 1500000000 },
  { symbol: 'GLRYH', name: 'Güler Yatırım Holding', sector: 'Holding', basePrice: 8.50, yahooSymbol: 'GLRYH.IS', marketCap: 850000000 },
  { symbol: 'ISGSY', name: 'İş Girişim Sermayesi', sector: 'Finans', basePrice: 20.00, yahooSymbol: 'ISGSY.IS', marketCap: 1000000000 },
  { symbol: 'TNZTP', name: 'Tapdi Oksijen Sağlık', sector: 'Sertifika', basePrice: 5.50, yahooSymbol: 'TNZTP.IS', marketCap: 550000000 },
  { symbol: 'MEGMT', name: 'Mega Metal', sector: 'Metal', basePrice: 55.00, yahooSymbol: 'MEGMT.IS', marketCap: 2750000000 },
  { symbol: 'VERTU', name: 'Verusaturk Girişim', sector: 'Finans', basePrice: 7.00, yahooSymbol: 'VERTU.IS', marketCap: 700000000 },
  // === EK BIST HİSSELERİ - Paket 2 ===
  { symbol: 'ADEL', name: 'Adel Kalemcilik', sector: 'Kırtasiye', basePrice: 210.00, yahooSymbol: 'ADEL.IS', marketCap: 5000000000 },
  { symbol: 'ADESE', name: 'Adese Gayrimenkul Yatırım', sector: 'Perakende', basePrice: 2.50, yahooSymbol: 'ADESE.IS', marketCap: 350000000 },
  { symbol: 'AGROT', name: 'Agrotech Yüksek Teknoloji', sector: 'Makine', basePrice: 14.80, yahooSymbol: 'AGROT.IS', marketCap: 420000000 },
  { symbol: 'AKSUE', name: 'Aksu Enerji', sector: 'Enerji', basePrice: 5.60, yahooSymbol: 'AKSUE.IS', marketCap: 380000000 },
  { symbol: 'AKYHO', name: 'Akdeniz Yatırım Holding', sector: 'Holding', basePrice: 4.20, yahooSymbol: 'AKYHO.IS', marketCap: 320000000 },
  { symbol: 'ALCAR', name: 'Alarko Carrier', sector: 'Makine', basePrice: 78.50, yahooSymbol: 'ALCAR.IS', marketCap: 7800000000 },
  { symbol: 'ANELE', name: 'Anel Elektrik', sector: 'Elektrik', basePrice: 7.90, yahooSymbol: 'ANELE.IS', marketCap: 650000000 },
  { symbol: 'ANGEN', name: 'Anatolia Genetik', sector: 'Biyoteknoloji', basePrice: 18.40, yahooSymbol: 'ANGEN.IS', marketCap: 920000000 },
  { symbol: 'ARASE', name: 'Doğu Aras Enerji Yatırımları', sector: 'Enerji', basePrice: 3.80, yahooSymbol: 'ARASE.IS', marketCap: 290000000 },
  { symbol: 'ARZUM', name: 'Arzum Elektrikli Ev Aletleri', sector: 'Ev Aletleri', basePrice: 28.50, yahooSymbol: 'ARZUM.IS', marketCap: 2200000000 },
  { symbol: 'ATATP', name: 'ATP Bilgisayar', sector: 'Teknoloji', basePrice: 15.20, yahooSymbol: 'ATATP.IS', marketCap: 760000000 },
  { symbol: 'ATEKS', name: 'Ak Tekstil', sector: 'Tekstil', basePrice: 6.30, yahooSymbol: 'ATEKS.IS', marketCap: 410000000 },
  { symbol: 'ATLAS', name: 'Atlas Yatırım Ortaklığı', sector: 'Finans', basePrice: 4.80, yahooSymbol: 'ATLAS.IS', marketCap: 340000000 },
  { symbol: 'AVGYO', name: 'Avrasya GYO', sector: 'GYO', basePrice: 3.50, yahooSymbol: 'AVGYO.IS', marketCap: 270000000 },
  { symbol: 'AVPGY', name: 'Avrupakent GYO', sector: 'GYO', basePrice: 2.90, yahooSymbol: 'AVPGY.IS', marketCap: 220000000 },
  { symbol: 'BASCM', name: 'Baştaş Çimento', sector: 'Çimento', basePrice: 14.50, yahooSymbol: 'BASCM.IS', marketCap: 850000000 },
  { symbol: 'BASGZ', name: 'Başkent Doğalgaz', sector: 'Enerji', basePrice: 6.80, yahooSymbol: 'BASGZ.IS', marketCap: 490000000 },
  { symbol: 'BFREN', name: 'Bosch Fren Sistemleri', sector: 'Otomotiv', basePrice: 42.30, yahooSymbol: 'BFREN.IS', marketCap: 3200000000 },
  { symbol: 'BIGCH', name: 'Büyük Şefler (BigChefs)', sector: 'Gıda', basePrice: 13.70, yahooSymbol: 'BIGCH.IS', marketCap: 680000000 },
  { symbol: 'BMSTL', name: 'BMS Birleşik Metal', sector: 'Metal', basePrice: 19.60, yahooSymbol: 'BMSTL.IS', marketCap: 1100000000 },
  { symbol: 'BORLS', name: 'Borlease Otomotiv', sector: 'Lojistik', basePrice: 56.40, yahooSymbol: 'BORLS.IS', marketCap: 4500000000 },
  { symbol: 'BORSK', name: 'Bor Şeker Fabrikası', sector: 'Gıda', basePrice: 7.20, yahooSymbol: 'BORSK.IS', marketCap: 430000000 },
  { symbol: 'BRKO', name: 'Birko Birleşik Koyunlulular', sector: 'Tekstil', basePrice: 3.90, yahooSymbol: 'BRKO.IS', marketCap: 280000000 },
  { symbol: 'BRKVY', name: 'Birikim Varlık Yönetim', sector: 'İnşaat', basePrice: 16.40, yahooSymbol: 'BRKVY.IS', marketCap: 890000000 },
  { symbol: 'BRYAT', name: 'Borusan Yatırım', sector: 'Holding', basePrice: 48.30, yahooSymbol: 'BRYAT.IS', marketCap: 3800000000 },
  { symbol: 'BSOKE', name: 'Batısöke Çimento', sector: 'Çimento', basePrice: 5.10, yahooSymbol: 'BSOKE.IS', marketCap: 370000000 },
  { symbol: 'CEMAS', name: 'Çemaş Döküm', sector: 'Metal', basePrice: 4.70, yahooSymbol: 'CEMAS.IS', marketCap: 320000000 },
  { symbol: 'CMENT', name: 'Çimentaş İzmir Çimento', sector: 'Çimento', basePrice: 8.30, yahooSymbol: 'CMENT.IS', marketCap: 540000000 },
  { symbol: 'COSMO', name: 'Cosmos Yatırım Holding', sector: 'Holding', basePrice: 5.30, yahooSymbol: 'COSMO.IS', marketCap: 360000000 },
  { symbol: 'DERIM', name: 'Derimod Konfeksiyon', sector: 'Tekstil', basePrice: 32.70, yahooSymbol: 'DERIM.IS', marketCap: 2500000000 },
  { symbol: 'DGATE', name: 'Datagate Bilgisayar', sector: 'Teknoloji', basePrice: 24.80, yahooSymbol: 'DGATE.IS', marketCap: 1500000000 },
  { symbol: 'DIRIT', name: 'Diriteks Diriliş Tekstil', sector: 'Tekstil', basePrice: 7.50, yahooSymbol: 'DIRIT.IS', marketCap: 450000000 },
  { symbol: 'DMRGD', name: 'DMR Unlu Mamüller', sector: 'Gıda', basePrice: 10.20, yahooSymbol: 'DMRGD.IS', marketCap: 580000000 },
  { symbol: 'EDIP', name: 'Edip İplik Sanayi', sector: 'Tekstil', basePrice: 4.30, yahooSymbol: 'EDIP.IS', marketCap: 280000000 },
  { symbol: 'EGPRO', name: 'Ege Profil', sector: 'Plastik', basePrice: 55.20, yahooSymbol: 'EGPRO.IS', marketCap: 4200000000 },
  { symbol: 'EKSUN', name: 'Eksun Gıda Tarım', sector: 'Gıda', basePrice: 14.30, yahooSymbol: 'EKSUN.IS', marketCap: 780000000 },
  { symbol: 'ELITE', name: 'Elite Naturel Organik Gıda', sector: 'Gıda', basePrice: 38.60, yahooSymbol: 'ELITE.IS', marketCap: 2800000000 },
  { symbol: 'ENSRI', name: 'Ensari Deri Sanayi', sector: 'Tekstil', basePrice: 8.90, yahooSymbol: 'ENSRI.IS', marketCap: 520000000 },
  { symbol: 'ETILR', name: 'Etiler Gıda ve Ticaret', sector: 'Gıda', basePrice: 12.40, yahooSymbol: 'ETILR.IS', marketCap: 680000000 },
  { symbol: 'ETYAT', name: 'Euro Trend Yatırım Ortaklığı', sector: 'Finans', basePrice: 2.80, yahooSymbol: 'ETYAT.IS', marketCap: 200000000 },
  { symbol: 'FLAP', name: 'Flap Kongre Toplantı', sector: 'Turizm', basePrice: 7.80, yahooSymbol: 'FLAP.IS', marketCap: 460000000 },
  { symbol: 'FORTE', name: 'Forte Bilgi İletişim', sector: 'Teknoloji', basePrice: 16.90, yahooSymbol: 'FORTE.IS', marketCap: 920000000 },
  { symbol: 'GEDZA', name: 'Gediz Ambalaj', sector: 'Ambalaj', basePrice: 18.30, yahooSymbol: 'GEDZA.IS', marketCap: 1050000000 },
  { symbol: 'GEREL', name: 'Gersan Elektrik', sector: 'Elektrik', basePrice: 9.40, yahooSymbol: 'GEREL.IS', marketCap: 560000000 },
  { symbol: 'GLCVY', name: 'Gelecek Varlık Yönetimi', sector: 'Finans', basePrice: 6.20, yahooSymbol: 'GLCVY.IS', marketCap: 420000000 },
  { symbol: 'GSDDE', name: 'GSD Denizcilik', sector: 'Denizcilik', basePrice: 3.40, yahooSymbol: 'GSDDE.IS', marketCap: 240000000 },
  { symbol: 'HATSN', name: 'Hat-San Gemi İnşa', sector: 'Denizcilik', basePrice: 11.50, yahooSymbol: 'HATSN.IS', marketCap: 640000000 },
  { symbol: 'HEDEF', name: 'Hedef Holding', sector: 'Holding', basePrice: 4.60, yahooSymbol: 'HEDEF.IS', marketCap: 330000000 },
  { symbol: 'HKTM', name: 'Hidropar Hareket Kontrol', sector: 'Makine', basePrice: 36.40, yahooSymbol: 'HKTM.IS', marketCap: 2700000000 },
  { symbol: 'ICUGS', name: 'ICU Girişim Sermayesi Yatırım Ortaklığı', sector: 'Gıda', basePrice: 7.10, yahooSymbol: 'ICUGS.IS', marketCap: 430000000 },
  { symbol: 'IDGYO', name: 'İdealist GYO', sector: 'GYO', basePrice: 3.80, yahooSymbol: 'IDGYO.IS', marketCap: 260000000 },
  { symbol: 'IHGZT', name: 'İhlas Gazetecilik', sector: 'Medya', basePrice: 2.20, yahooSymbol: 'IHGZT.IS', marketCap: 160000000 },
  { symbol: 'IHLAS', name: 'İhlas Holding', sector: 'Holding', basePrice: 1.90, yahooSymbol: 'IHLAS.IS', marketCap: 450000000 },
  { symbol: 'IHLGM', name: 'İhlas Gayrimenkul', sector: 'İnşaat', basePrice: 2.60, yahooSymbol: 'IHLGM.IS', marketCap: 310000000 },
  { symbol: 'IHYAY', name: 'İhlas Yayın Holding', sector: 'Medya', basePrice: 1.50, yahooSymbol: 'IHYAY.IS', marketCap: 120000000 },
  { symbol: 'IMASM', name: 'İmaş Makine Sanayi', sector: 'Makine', basePrice: 8.40, yahooSymbol: 'IMASM.IS', marketCap: 500000000 },
  { symbol: 'INVEO', name: 'Inveo Yatırım Holding', sector: 'Holding', basePrice: 42.80, yahooSymbol: 'INVEO.IS', marketCap: 3400000000 },
  { symbol: 'IEYHO', name: 'Işıklar Enerji ve Yapı Holding', sector: 'Finans', basePrice: 15.60, yahooSymbol: 'IEYHO.IS', marketCap: 870000000 },
  { symbol: 'KAPLM', name: 'Kaplamin Ambalaj', sector: 'Ambalaj', basePrice: 20.30, yahooSymbol: 'KAPLM.IS', marketCap: 1200000000 },
  { symbol: 'KGYO', name: 'Koray GYO', sector: 'GYO', basePrice: 8.50, yahooSymbol: 'KGYO.IS', marketCap: 540000000 },
  { symbol: 'KLSYN', name: 'Koleksiyon Mobilya', sector: 'Mobilya', basePrice: 7.60, yahooSymbol: 'KLSYN.IS', marketCap: 450000000 },
  { symbol: 'KMPUR', name: 'Kimteks Poliüretan', sector: 'Kimya', basePrice: 29.40, yahooSymbol: 'KMPUR.IS', marketCap: 2100000000 },
  { symbol: 'KOPOL', name: 'Koza Polyester', sector: 'Kimya', basePrice: 5.40, yahooSymbol: 'KOPOL.IS', marketCap: 370000000 },
  { symbol: 'KRVGD', name: 'Kervan Gıda Sanayi', sector: 'Gıda', basePrice: 140.50, yahooSymbol: 'KRVGD.IS', marketCap: 12000000000 },
  { symbol: 'LIDER', name: 'LDR Turizm', sector: 'Finans', basePrice: 4.90, yahooSymbol: 'LIDER.IS', marketCap: 320000000 },
  { symbol: 'MAKIM', name: 'Makina Takım Endüstrisi', sector: 'Makine', basePrice: 17.80, yahooSymbol: 'MAKIM.IS', marketCap: 980000000 },
  { symbol: 'MARKA', name: 'Marka Yatırım Holding', sector: 'Holding', basePrice: 3.20, yahooSymbol: 'MARKA.IS', marketCap: 230000000 },
  { symbol: 'MEPET', name: 'Metro Petrol ve Tesisleri', sector: 'Enerji', basePrice: 5.80, yahooSymbol: 'MEPET.IS', marketCap: 390000000 },
  { symbol: 'MERCN', name: 'Mercan Kimya Sanayi', sector: 'Kimya', basePrice: 10.60, yahooSymbol: 'MERCN.IS', marketCap: 590000000 },
  { symbol: 'METRO', name: 'Metro Holding', sector: 'Holding', basePrice: 7.40, yahooSymbol: 'METRO.IS', marketCap: 450000000 },
  { symbol: 'MNDTR', name: 'Mondi Tire Kutsan', sector: 'Tekstil', basePrice: 4.50, yahooSymbol: 'MNDTR.IS', marketCap: 300000000 },
  { symbol: 'MOBTL', name: 'Mobiltel İletişim', sector: 'Telekomünikasyon', basePrice: 9.70, yahooSymbol: 'MOBTL.IS', marketCap: 560000000 },
  { symbol: 'MRGYO', name: 'Martı GYO', sector: 'GYO', basePrice: 2.30, yahooSymbol: 'MRGYO.IS', marketCap: 170000000 },
  { symbol: 'MZHLD', name: 'Mazhar Zorlu Holding', sector: 'Holding', basePrice: 3.70, yahooSymbol: 'MZHLD.IS', marketCap: 260000000 },
  { symbol: 'OYLUM', name: 'Oylum Sınai Yatırımlar', sector: 'Finans', basePrice: 3.40, yahooSymbol: 'OYLUM.IS', marketCap: 240000000 },
  { symbol: 'OZRDN', name: 'Özerden Ambalaj', sector: 'Plastik', basePrice: 12.10, yahooSymbol: 'OZRDN.IS', marketCap: 670000000 },
  { symbol: 'PENTA', name: 'Penta Teknoloji Ürünleri', sector: 'Teknoloji', basePrice: 42.50, yahooSymbol: 'PENTA.IS', marketCap: 3300000000 },
  { symbol: 'PETUN', name: 'Pınar Et ve Un Sanayi', sector: 'Gıda', basePrice: 21.80, yahooSymbol: 'PETUN.IS', marketCap: 1300000000 },
  { symbol: 'PKENT', name: 'Petrokent Turizm', sector: 'Turizm', basePrice: 80.50, yahooSymbol: 'PKENT.IS', marketCap: 6200000000 },
  { symbol: 'POLHO', name: 'Polisan Holding', sector: 'Holding', basePrice: 16.70, yahooSymbol: 'POLHO.IS', marketCap: 920000000 },
  { symbol: 'SANKO', name: 'Sanko Pazarlama', sector: 'Tekstil', basePrice: 6.80, yahooSymbol: 'SANKO.IS', marketCap: 410000000 },
  { symbol: 'SEKFK', name: 'Şeker Finansal Kiralama', sector: 'Finans', basePrice: 7.40, yahooSymbol: 'SEKFK.IS', marketCap: 440000000 },
  { symbol: 'SEKUR', name: 'Sekuro Plastik Ambalaj', sector: 'Plastik', basePrice: 19.80, yahooSymbol: 'SEKUR.IS', marketCap: 1100000000 },
  { symbol: 'SNPAM', name: 'Sönmez Pamuklu', sector: 'GYO', basePrice: 4.80, yahooSymbol: 'SNPAM.IS', marketCap: 330000000 },
  { symbol: 'SURGY', name: 'Sur GYO', sector: 'GYO', basePrice: 2.10, yahooSymbol: 'SURGY.IS', marketCap: 150000000 },
  { symbol: 'SUWEN', name: 'Suwen Tekstil Sanayi', sector: 'Tekstil', basePrice: 44.70, yahooSymbol: 'SUWEN.IS', marketCap: 3500000000 },
  { symbol: 'TATEN', name: 'Tatlıpınar Enerji Üretim', sector: 'Gıda', basePrice: 32.40, yahooSymbol: 'TATEN.IS', marketCap: 2400000000 },
  { symbol: 'TGSAS', name: 'TGS Dış Ticaret', sector: 'Ticaret', basePrice: 13.50, yahooSymbol: 'TGSAS.IS', marketCap: 740000000 },
  { symbol: 'TRILC', name: 'Turkcell Finansman', sector: 'Finans', basePrice: 78.90, yahooSymbol: 'TRILC.IS', marketCap: 6300000000 },
  { symbol: 'TSGYO', name: 'TSKB GYO', sector: 'GYO', basePrice: 5.60, yahooSymbol: 'TSGYO.IS', marketCap: 380000000 },
  { symbol: 'UFUK', name: 'Ufuk Yatırım Ortaklığı', sector: 'Finans', basePrice: 3.50, yahooSymbol: 'UFUK.IS', marketCap: 240000000 },
  { symbol: 'VANGD', name: 'Vanet Gıda', sector: 'Gıda', basePrice: 7.20, yahooSymbol: 'VANGD.IS', marketCap: 430000000 },
  { symbol: 'YAPRK', name: 'Yaprak Süt ve Besi', sector: 'Gıda', basePrice: 14.60, yahooSymbol: 'YAPRK.IS', marketCap: 800000000 },
  { symbol: 'YEOTK', name: 'Yeo Teknoloji Enerji', sector: 'Teknoloji', basePrice: 19.40, yahooSymbol: 'YEOTK.IS', marketCap: 1100000000 },
  { symbol: 'YGYO', name: 'Yeşil GYO', sector: 'GYO', basePrice: 2.80, yahooSymbol: 'YGYO.IS', marketCap: 200000000 },
  { symbol: 'ZEDUR', name: 'Zedur Enerji', sector: 'Enerji', basePrice: 5.40, yahooSymbol: 'ZEDUR.IS', marketCap: 360000000 },
  { symbol: 'ZRGYO', name: 'Ziraat GYO', sector: 'GYO', basePrice: 6.30, yahooSymbol: 'ZRGYO.IS', marketCap: 420000000 },
  { symbol: 'BARMA', name: 'Barem Ambalaj', sector: 'Madencilik', basePrice: 11.40, yahooSymbol: 'BARMA.IS', marketCap: 630000000 },
  { symbol: 'AKFIS', name: 'Akfen İnşaat', sector: 'Holding', basePrice: 12.80, yahooSymbol: 'AKFIS.IS', marketCap: 710000000 },
  { symbol: 'DGNMO', name: 'Doğanlar Mobilya', sector: 'Medya', basePrice: 8.40, yahooSymbol: 'DGNMO.IS', marketCap: 500000000 },
  { symbol: 'ECZYT', name: 'Eczacıbaşı Yatırım Ortaklığı', sector: 'Finans', basePrice: 17.40, yahooSymbol: 'ECZYT.IS', marketCap: 960000000 },
  { symbol: 'KZBGY', name: 'Kızılbük GYO', sector: 'GYO', basePrice: 5.30, yahooSymbol: 'KZBGY.IS', marketCap: 360000000 },
  { symbol: 'LMKDC', name: 'Limak Doğu Enerji', sector: 'Enerji', basePrice: 14.50, yahooSymbol: 'LMKDC.IS', marketCap: 800000000 },
  { symbol: 'LYDHO', name: 'Lydia Holding', sector: 'Holding', basePrice: 7.60, yahooSymbol: 'LYDHO.IS', marketCap: 460000000 },
  { symbol: 'OBAMS', name: 'Oba Makarnacılık', sector: 'Makine', basePrice: 6.90, yahooSymbol: 'OBAMS.IS', marketCap: 420000000 },
  { symbol: 'SANEL', name: 'Sanel Elektronik', sector: 'Elektrik', basePrice: 11.80, yahooSymbol: 'SANEL.IS', marketCap: 650000000 },
  { symbol: 'SRVGY', name: 'Servet GYO', sector: 'GYO', basePrice: 4.50, yahooSymbol: 'SRVGY.IS', marketCap: 310000000 },
  { symbol: 'TRCAS', name: 'Turcas Petrol', sector: 'Enerji', basePrice: 18.90, yahooSymbol: 'TRCAS.IS', marketCap: 1100000000 },
  { symbol: 'USDTR', name: 'İş Portföy Dolar Bonosu ETF', sector: 'Ticaret', basePrice: 8.40, yahooSymbol: 'USDTR.IS', marketCap: 500000000 },
  { symbol: 'VRGYO', name: 'Vera GYO', sector: 'GYO', basePrice: 3.90, yahooSymbol: 'VRGYO.IS', marketCap: 270000000 },
  { symbol: 'YESIL', name: 'Yeşil Yatırım Holding', sector: 'Holding', basePrice: 15.30, yahooSymbol: 'YESIL.IS', marketCap: 850000000 },

  // Yeni eklenen hisseler (eksik BIST hisseleri)
  { symbol: 'A1YEN', name: 'A1 Yenilenebilir Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'A1YEN.IS', marketCap: 0 },
  { symbol: 'AAGYO', name: 'Ağaoğlu GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'AAGYO.IS', marketCap: 0 },
  { symbol: 'ADGYO', name: 'Adra GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'ADGYO.IS', marketCap: 0 },
  { symbol: 'AGYO', name: 'Atakule GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'AGYO.IS', marketCap: 0 },
  { symbol: 'AKHAN', name: 'Akhan Un', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'AKHAN.IS', marketCap: 0 },
  { symbol: 'AKMGY', name: 'Akmerkez GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'AKMGY.IS', marketCap: 0 },
  { symbol: 'ALKA', name: 'Alkim Kağıt', sector: 'Kağıt', basePrice: 10.00, yahooSymbol: 'ALKA.IS', marketCap: 0 },
  { symbol: 'ALKLC', name: 'Altınkılıç Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'ALKLC.IS', marketCap: 0 },
  { symbol: 'RUZYE', name: 'RUZY Madencilik ve Enerji', sector: 'Madencilik', basePrice: 11.89, yahooSymbol: 'RUZYE.IS', marketCap: 0 },
  { symbol: 'ALVES', name: 'Alves Kablo', sector: 'Elektrik', basePrice: 10.00, yahooSymbol: 'ALVES.IS', marketCap: 0 },
  { symbol: 'APBDL', name: 'Ak Portföy BIST Banka Dışı Likit ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'APBDL.IS', marketCap: 0 },
  { symbol: 'APGLD', name: 'Ak Portföy Altın ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'APGLD.IS', marketCap: 0 },
  { symbol: 'APLIB', name: 'Ak Portföy BIST Likit Banka ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'APLIB.IS', marketCap: 0 },
  { symbol: 'APMDL', name: 'Ak Portföy BIST 100 ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'APMDL.IS', marketCap: 0 },
  { symbol: 'ARFYE', name: 'ARF Bio Yenilenebilir Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'ARFYE.IS', marketCap: 0 },
  { symbol: 'ARMGD', name: 'Armada Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'ARMGD.IS', marketCap: 0 },
  { symbol: 'ARTMS', name: 'Artemis Halı', sector: 'Tekstil', basePrice: 10.00, yahooSymbol: 'ARTMS.IS', marketCap: 0 },
  { symbol: 'ASGYO', name: 'Asce GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'ASGYO.IS', marketCap: 0 },
  { symbol: 'ATAKP', name: 'Atakey Patates', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'ATAKP.IS', marketCap: 0 },
  { symbol: 'ATATR', name: 'Ata Turizm', sector: 'Turizm', basePrice: 10.00, yahooSymbol: 'ATATR.IS', marketCap: 0 },
  { symbol: 'ATSYH', name: 'Atlantis Yatırım Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'ATSYH.IS', marketCap: 0 },
  { symbol: 'AVTUR', name: 'Avrasya Petrol Turizm', sector: 'Turizm', basePrice: 10.00, yahooSymbol: 'AVTUR.IS', marketCap: 0 },
  { symbol: 'AYES', name: 'Ayes Çelik Hasır', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'AYES.IS', marketCap: 0 },
  { symbol: 'AZTEK', name: 'Aztek Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'AZTEK.IS', marketCap: 0 },
  { symbol: 'BAHKM', name: 'Bahadır Kimya', sector: 'Kimya', basePrice: 10.00, yahooSymbol: 'BAHKM.IS', marketCap: 0 },
  { symbol: 'BALSU', name: 'Balsu Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'BALSU.IS', marketCap: 0 },
  { symbol: 'BEGYO', name: 'Batı Ege GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'BEGYO.IS', marketCap: 0 },
  { symbol: 'BESLR', name: 'Besler Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'BESLR.IS', marketCap: 0 },
  { symbol: 'BESTE', name: 'Best Brands Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'BESTE.IS', marketCap: 0 },
  { symbol: 'BIENY', name: 'Bien Yapı', sector: 'İnşaat', basePrice: 10.00, yahooSymbol: 'BIENY.IS', marketCap: 0 },
  { symbol: 'BIGEN', name: 'Birleşim Grup Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'BIGEN.IS', marketCap: 0 },
  { symbol: 'BIGTK', name: 'Big Medya Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'BIGTK.IS', marketCap: 0 },
  { symbol: 'BINBN', name: 'Bin Ulaşım Akıllı Şehir', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'BINBN.IS', marketCap: 0 },
  { symbol: 'BLUME', name: 'Blume Metal Kimya', sector: 'Kimya', basePrice: 10.00, yahooSymbol: 'BLUME.IS', marketCap: 0 },
  { symbol: 'BMSCH', name: 'BMS Çelik Hasır', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'BMSCH.IS', marketCap: 0 },
  { symbol: 'BRKSN', name: 'Berkosan Yalıtım', sector: 'İnşaat', basePrice: 10.00, yahooSymbol: 'BRKSN.IS', marketCap: 0 },
  { symbol: 'BULGS', name: 'Bulls GSYO', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'BULGS.IS', marketCap: 0 },
  { symbol: 'BYDNR', name: 'Baydöner Restoranları', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'BYDNR.IS', marketCap: 0 },
  { symbol: 'CATES', name: 'Çateş Elektrik', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'CATES.IS', marketCap: 0 },
  { symbol: 'CGCAM', name: 'Çağdaş Cam', sector: 'Cam', basePrice: 10.00, yahooSymbol: 'CGCAM.IS', marketCap: 0 },
  { symbol: 'CRDFA', name: 'Creditwest Faktoring', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'CRDFA.IS', marketCap: 0 },
  { symbol: 'CRFSA', name: 'CarrefourSA', sector: 'Perakende', basePrice: 10.00, yahooSymbol: 'CRFSA.IS', marketCap: 0 },
  { symbol: 'DCTTR', name: 'DCT Trading', sector: 'Ticaret', basePrice: 10.00, yahooSymbol: 'DCTTR.IS', marketCap: 0 },
  { symbol: 'DOFER', name: 'Dofer Yapı Malzemeleri', sector: 'İnşaat', basePrice: 10.00, yahooSymbol: 'DOFER.IS', marketCap: 0 },
  { symbol: 'DOFRB', name: 'DOF Robotik', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'DOFRB.IS', marketCap: 0 },
  { symbol: 'DOGUB', name: 'Doğusan Boru', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'DOGUB.IS', marketCap: 0 },
  { symbol: 'DSTKF', name: 'Destek Finans Faktoring', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'DSTKF.IS', marketCap: 0 },
  { symbol: 'DUNYH', name: 'Dünya Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'DUNYH.IS', marketCap: 0 },
  { symbol: 'DURKN', name: 'Durukan Şekerleme', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'DURKN.IS', marketCap: 0 },
  { symbol: 'ECOGR', name: 'Ecogreen Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'ECOGR.IS', marketCap: 0 },
  { symbol: 'EFOR', name: 'Efor Yatırım', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'EFOR.IS', marketCap: 0 },
  { symbol: 'EGEGY', name: 'Ege Yapı GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'EGEGY.IS', marketCap: 0 },
  { symbol: 'EKOS', name: 'Ekos Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'EKOS.IS', marketCap: 0 },
  { symbol: 'EMPAE', name: 'Empa Elektronik', sector: 'Elektronik', basePrice: 10.00, yahooSymbol: 'EMPAE.IS', marketCap: 0 },
  { symbol: 'ENDAE', name: 'Enda Enerji Holding', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'ENDAE.IS', marketCap: 0 },
  { symbol: 'ENERY', name: 'Enerya Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'ENERY.IS', marketCap: 0 },
  { symbol: 'ENPRA', name: 'Enpara Bank', sector: 'Bankacılık', basePrice: 10.00, yahooSymbol: 'ENPRA.IS', marketCap: 0 },
  { symbol: 'ENTRA', name: 'IC Enterra Yenilenebilir Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'ENTRA.IS', marketCap: 0 },
  { symbol: 'ERBOS', name: 'Erbosan Erciyas Boru', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'ERBOS.IS', marketCap: 0 },
  { symbol: 'ERCB', name: 'Erciyas Çelik Boru', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'ERCB.IS', marketCap: 0 },
  { symbol: 'ESCAR', name: 'Escar Filo Kiralama', sector: 'Ulaşım', basePrice: 10.00, yahooSymbol: 'ESCAR.IS', marketCap: 0 },
  { symbol: 'ESEN', name: 'Esenboğa Elektrik', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'ESEN.IS', marketCap: 0 },
  { symbol: 'EUHOL', name: 'Euro Yatırım Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'EUHOL.IS', marketCap: 0 },
  { symbol: 'EUREN', name: 'Europen Endüstri', sector: 'Sanayi', basePrice: 10.00, yahooSymbol: 'EUREN.IS', marketCap: 0 },
  { symbol: 'EYGYO', name: 'EYG GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'EYGYO.IS', marketCap: 0 },
  { symbol: 'FRMPL', name: 'Formül Plastik Metal', sector: 'Plastik', basePrice: 10.00, yahooSymbol: 'FRMPL.IS', marketCap: 0 },
  { symbol: 'GATEG', name: 'Gate Group Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'GATEG.IS', marketCap: 0 },
  { symbol: 'GENIL', name: 'Gen İlaç Sağlık', sector: 'Sağlık', basePrice: 10.00, yahooSymbol: 'GENIL.IS', marketCap: 0 },
  { symbol: 'GENKM', name: 'Gentaş Kimya', sector: 'Kimya', basePrice: 10.00, yahooSymbol: 'GENKM.IS', marketCap: 0 },
  { symbol: 'GIPTA', name: 'Gipta Kırtasiye', sector: 'Kırtasiye', basePrice: 10.00, yahooSymbol: 'GIPTA.IS', marketCap: 0 },
  { symbol: 'GLRMK', name: 'Gülermak Ağır Sanayi', sector: 'Sanayi', basePrice: 10.00, yahooSymbol: 'GLRMK.IS', marketCap: 0 },
  { symbol: 'GMTAS', name: 'Gimat Mağazacılık', sector: 'Perakende', basePrice: 10.00, yahooSymbol: 'GMTAS.IS', marketCap: 0 },
  { symbol: 'GOKNR', name: 'Göknur Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'GOKNR.IS', marketCap: 0 },
  { symbol: 'GOZDE', name: 'Gözde Girişim Sermayesi', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'GOZDE.IS', marketCap: 0 },
  { symbol: 'GRNYO', name: 'Garanti Yatırım Ortaklığı', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'GRNYO.IS', marketCap: 0 },
  { symbol: 'GRTHO', name: 'Grainturk Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'GRTHO.IS', marketCap: 0 },
  { symbol: 'GUNDG', name: 'Gündoğdu Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'GUNDG.IS', marketCap: 0 },
  { symbol: 'GZNMI', name: 'Gezinomi Turizm', sector: 'Turizm', basePrice: 10.00, yahooSymbol: 'GZNMI.IS', marketCap: 0 },
  { symbol: 'HDFGS', name: 'Hedef Girişim Sermayesi', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'HDFGS.IS', marketCap: 0 },
  { symbol: 'HOROZ', name: 'Horoz Lojistik', sector: 'Lojistik', basePrice: 10.00, yahooSymbol: 'HOROZ.IS', marketCap: 0 },
  { symbol: 'HRKET', name: 'Hareket Proje Taşımacılığı', sector: 'Lojistik', basePrice: 10.00, yahooSymbol: 'HRKET.IS', marketCap: 0 },
  { symbol: 'IHAAS', name: 'İhlas Haber Ajansı', sector: 'Medya', basePrice: 10.00, yahooSymbol: 'IHAAS.IS', marketCap: 0 },
  { symbol: 'INTEK', name: 'Innosa Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'INTEK.IS', marketCap: 0 },
  { symbol: 'INVES', name: 'Investco Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'INVES.IS', marketCap: 0 },
  { symbol: 'ISATR', name: 'İş Bankası A Kurucu', sector: 'Bankacılık', basePrice: 10.00, yahooSymbol: 'ISATR.IS', marketCap: 0 },
  { symbol: 'ISBTR', name: 'İş Bankası B Kurucu', sector: 'Bankacılık', basePrice: 10.00, yahooSymbol: 'ISBTR.IS', marketCap: 0 },
  { symbol: 'ISFIN', name: 'İş Finansal Kiralama', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'ISFIN.IS', marketCap: 0 },
  { symbol: 'ISGLK', name: 'İş Portföy Altın Katılım ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ISGLK.IS', marketCap: 0 },
  { symbol: 'ISKPL', name: 'Işık Plastik', sector: 'Plastik', basePrice: 10.00, yahooSymbol: 'ISKPL.IS', marketCap: 0 },
  { symbol: 'ISKUR', name: 'İş Bankası C Kurucu', sector: 'Bankacılık', basePrice: 10.00, yahooSymbol: 'ISKUR.IS', marketCap: 0 },
  { symbol: 'ISYAT', name: 'İş Yatırım Ortaklığı', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'ISYAT.IS', marketCap: 0 },
  { symbol: 'IZINV', name: 'İz Yatırım Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'IZINV.IS', marketCap: 0 },
  { symbol: 'KBORU', name: 'Kuzey Boru', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'KBORU.IS', marketCap: 0 },
  { symbol: 'KCAER', name: 'Kocaer Çelik', sector: 'Demir-Çelik', basePrice: 10.00, yahooSymbol: 'KCAER.IS', marketCap: 0 },
  { symbol: 'KIMMR', name: 'Kim Market Ersan Alışveriş', sector: 'Perakende', basePrice: 10.00, yahooSymbol: 'KIMMR.IS', marketCap: 0 },
  { symbol: 'KLKIM', name: 'Kalekim Kimya', sector: 'Kimya', basePrice: 10.00, yahooSymbol: 'KLKIM.IS', marketCap: 0 },
  { symbol: 'KLRHO', name: 'Kiler Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'KLRHO.IS', marketCap: 0 },
  { symbol: 'KLYPV', name: 'Kalyon Güneş Teknolojileri', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'KLYPV.IS', marketCap: 0 },
  { symbol: 'KOCMT', name: 'Koç Metalurji', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'KOCMT.IS', marketCap: 0 },
  { symbol: 'KONKA', name: 'Konya Kağıt', sector: 'Kağıt', basePrice: 10.00, yahooSymbol: 'KONKA.IS', marketCap: 0 },
  { symbol: 'KOTON', name: 'Koton Mağazacılık', sector: 'Perakende', basePrice: 10.00, yahooSymbol: 'KOTON.IS', marketCap: 0 },
  { symbol: 'KRPLS', name: 'Koroplast Ambalaj', sector: 'Plastik', basePrice: 10.00, yahooSymbol: 'KRPLS.IS', marketCap: 0 },
  { symbol: 'KRSTL', name: 'Kristal Kola', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'KRSTL.IS', marketCap: 0 },
  { symbol: 'KRTEK', name: 'Karsu Tekstil', sector: 'Tekstil', basePrice: 10.00, yahooSymbol: 'KRTEK.IS', marketCap: 0 },
  { symbol: 'KUVVA', name: 'Kuvva Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'KUVVA.IS', marketCap: 0 },
  { symbol: 'KZGYO', name: 'Kuzugrup GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'KZGYO.IS', marketCap: 0 },
  { symbol: 'LILAK', name: 'Lila Kağıt', sector: 'Kağıt', basePrice: 10.00, yahooSymbol: 'LILAK.IS', marketCap: 0 },
  { symbol: 'LRSHO', name: 'Loras Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'LRSHO.IS', marketCap: 0 },
  { symbol: 'LXGYO', name: 'Luxera GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'LXGYO.IS', marketCap: 0 },
  { symbol: 'LYDYE', name: 'Lydia Yeşil Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'LYDYE.IS', marketCap: 0 },
  { symbol: 'MACKO', name: 'Mackolik', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'MACKO.IS', marketCap: 0 },
  { symbol: 'MARBL', name: 'Tureks Turunç Madencilik', sector: 'Madencilik', basePrice: 10.00, yahooSymbol: 'MARBL.IS', marketCap: 0 },
  { symbol: 'MARMR', name: 'Marmara Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'MARMR.IS', marketCap: 0 },
  { symbol: 'MCARD', name: 'Metropal Kurumsal Hizmetler', sector: 'Hizmet', basePrice: 10.00, yahooSymbol: 'MCARD.IS', marketCap: 0 },
  { symbol: 'MEKAG', name: 'Meka Global Makine', sector: 'Makine', basePrice: 10.00, yahooSymbol: 'MEKAG.IS', marketCap: 0 },
  { symbol: 'MEYSU', name: 'Meysu Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'MEYSU.IS', marketCap: 0 },
  { symbol: 'MHRGY', name: 'MHR GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'MHRGY.IS', marketCap: 0 },
  { symbol: 'MMCAS', name: 'MMC Sanayi Yatırım', sector: 'Sanayi', basePrice: 10.00, yahooSymbol: 'MMCAS.IS', marketCap: 0 },
  { symbol: 'MOGAN', name: 'Mogan Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'MOGAN.IS', marketCap: 0 },
  { symbol: 'MOPAS', name: 'Mopaş Marketçilik', sector: 'Perakende', basePrice: 10.00, yahooSymbol: 'MOPAS.IS', marketCap: 0 },
  { symbol: 'MTRKS', name: 'Matriks Finansal Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'MTRKS.IS', marketCap: 0 },
  { symbol: 'NETCD', name: 'Netcad Yazılım', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'NETCD.IS', marketCap: 0 },
  { symbol: 'NPTLR', name: 'Nurol Portföy TLREF ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'NPTLR.IS', marketCap: 0 },
  { symbol: 'ODINE', name: 'Odine Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'ODINE.IS', marketCap: 0 },
  { symbol: 'OFSYM', name: 'Ofis Yem Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'OFSYM.IS', marketCap: 0 },
  { symbol: 'ONRYT', name: 'Onur Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'ONRYT.IS', marketCap: 0 },
  { symbol: 'OPTGY', name: 'Osmanlı Portföy GYO ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'OPTGY.IS', marketCap: 0 },
  { symbol: 'OPTLR', name: 'Osmanlı Portföy TLREF ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'OPTLR.IS', marketCap: 0 },
  { symbol: 'OTTO', name: 'Otto Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'OTTO.IS', marketCap: 0 },
  { symbol: 'OYAYO', name: 'Oyak Yatırım Ortaklığı', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'OYAYO.IS', marketCap: 0 },
  { symbol: 'OYYAT', name: 'Oyak Yatırım Menkul Değerler', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'OYYAT.IS', marketCap: 0 },
  { symbol: 'OZATD', name: 'Özata Denizcilik', sector: 'Denizcilik', basePrice: 10.00, yahooSymbol: 'OZATD.IS', marketCap: 0 },
  { symbol: 'OZSUB', name: 'Özsu Balık', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'OZSUB.IS', marketCap: 0 },
  { symbol: 'OZYSR', name: 'Özyaşar Tel', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'OZYSR.IS', marketCap: 0 },
  { symbol: 'PAHOL', name: 'Pasifik Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'PAHOL.IS', marketCap: 0 },
  { symbol: 'PAMEL', name: 'Pamel Elektrik', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'PAMEL.IS', marketCap: 0 },
  { symbol: 'PASEU', name: 'Pasifik Eurasia Lojistik', sector: 'Lojistik', basePrice: 10.00, yahooSymbol: 'PASEU.IS', marketCap: 0 },
  { symbol: 'PATEK', name: 'Pasifik Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'PATEK.IS', marketCap: 0 },
  { symbol: 'PNLSN', name: 'Panelsan Çatı Cephe', sector: 'İnşaat', basePrice: 10.00, yahooSymbol: 'PNLSN.IS', marketCap: 0 },
  { symbol: 'PRDGS', name: 'Pardus Girişim Sermayesi', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'PRDGS.IS', marketCap: 0 },
  { symbol: 'PSGYO', name: 'Pasifik GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'PSGYO.IS', marketCap: 0 },
  { symbol: 'QNBFK', name: 'QNB Finansal Kiralama', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'QNBFK.IS', marketCap: 0 },
  { symbol: 'QNBTR', name: 'QNB Bank', sector: 'Bankacılık', basePrice: 10.00, yahooSymbol: 'QNBTR.IS', marketCap: 0 },
  { symbol: 'QTEMZ', name: 'DJ İstanbul 20 ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'QTEMZ.IS', marketCap: 0 },
  { symbol: 'REEDR', name: 'Reeder Teknoloji', sector: 'Teknoloji', basePrice: 10.00, yahooSymbol: 'REEDR.IS', marketCap: 0 },
  { symbol: 'RGYAS', name: 'Rönesans GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'RGYAS.IS', marketCap: 0 },
  { symbol: 'RNPOL', name: 'Rainbow Polikarbonat', sector: 'Plastik', basePrice: 10.00, yahooSymbol: 'RNPOL.IS', marketCap: 0 },
  { symbol: 'RODRG', name: 'Rodrigo Tekstil', sector: 'Tekstil', basePrice: 10.00, yahooSymbol: 'RODRG.IS', marketCap: 0 },
  { symbol: 'RUZYE', name: 'Ruzy Madencilik Enerji', sector: 'Madencilik', basePrice: 10.00, yahooSymbol: 'RUZYE.IS', marketCap: 0 },
  { symbol: 'SAFKR', name: 'Safkar Ege Soğutmacılık', sector: 'Sanayi', basePrice: 10.00, yahooSymbol: 'SAFKR.IS', marketCap: 0 },
  { symbol: 'SDTTR', name: 'SDT Uzay Savunma', sector: 'Savunma', basePrice: 10.00, yahooSymbol: 'SDTTR.IS', marketCap: 0 },
  { symbol: 'SEGMN', name: 'Segmen Kardeşler Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'SEGMN.IS', marketCap: 0 },
  { symbol: 'SEGYO', name: 'Şeker GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'SEGYO.IS', marketCap: 0 },
  { symbol: 'SERNT', name: 'Seranit Granit Seramik', sector: 'Seramik', basePrice: 10.00, yahooSymbol: 'SERNT.IS', marketCap: 0 },
  { symbol: 'SEYKM', name: 'Seyitler Kimya', sector: 'Kimya', basePrice: 10.00, yahooSymbol: 'SEYKM.IS', marketCap: 0 },
  { symbol: 'SKYLP', name: 'Skyalp Finansal Teknoloji', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'SKYLP.IS', marketCap: 0 },
  { symbol: 'SKYMD', name: 'Şeker Yatırım', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'SKYMD.IS', marketCap: 0 },
  { symbol: 'SMRVA', name: 'Sümer Varlık Yönetim', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'SMRVA.IS', marketCap: 0 },
  { symbol: 'SNICA', name: 'Sanica Isı', sector: 'Sanayi', basePrice: 10.00, yahooSymbol: 'SNICA.IS', marketCap: 0 },
  { symbol: 'SODSN', name: 'Sodaş Sodyum', sector: 'Kimya', basePrice: 10.00, yahooSymbol: 'SODSN.IS', marketCap: 0 },
  { symbol: 'SOKE', name: 'Söke Değirmencilik', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'SOKE.IS', marketCap: 0 },
  { symbol: 'SUNTK', name: 'Sun Tekstil', sector: 'Tekstil', basePrice: 10.00, yahooSymbol: 'SUNTK.IS', marketCap: 0 },
  { symbol: 'SVGYO', name: 'Savur GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'SVGYO.IS', marketCap: 0 },
  { symbol: 'TABGD', name: 'TAB Gıda', sector: 'Gıda', basePrice: 10.00, yahooSymbol: 'TABGD.IS', marketCap: 0 },
  { symbol: 'TARKM', name: 'Tarkim Bitki Koruma', sector: 'Tarım', basePrice: 10.00, yahooSymbol: 'TARKM.IS', marketCap: 0 },
  { symbol: 'TCKRC', name: 'Kıraç Galvaniz', sector: 'Metal', basePrice: 10.00, yahooSymbol: 'TCKRC.IS', marketCap: 0 },
  { symbol: 'TEHOL', name: 'Tera Yatırım Teknoloji Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'TEHOL.IS', marketCap: 0 },
  { symbol: 'TEKTU', name: 'Tek-Art İnşaat Turizm', sector: 'Turizm', basePrice: 10.00, yahooSymbol: 'TEKTU.IS', marketCap: 0 },
  { symbol: 'TERA', name: 'Tera Yatırım Menkul Değerler', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'TERA.IS', marketCap: 0 },
  { symbol: 'TRALT', name: 'Türk Altın İşletmeleri', sector: 'Madencilik', basePrice: 10.00, yahooSymbol: 'TRALT.IS', marketCap: 0 },
  { symbol: 'TRENJ', name: 'TR Doğal Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'TRENJ.IS', marketCap: 0 },
  { symbol: 'TRHOL', name: 'Tera Finansal Yatırımlar Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'TRHOL.IS', marketCap: 0 },
  { symbol: 'TRMET', name: 'TR Anadolu Metal Madencilik', sector: 'Madencilik', basePrice: 10.00, yahooSymbol: 'TRMET.IS', marketCap: 0 },
  { symbol: 'UCAYM', name: 'Ucay Mühendislik Enerji', sector: 'Enerji', basePrice: 10.00, yahooSymbol: 'UCAYM.IS', marketCap: 0 },
  { symbol: 'ULAS', name: 'Ulaşlar Turizm Enerji', sector: 'Turizm', basePrice: 10.00, yahooSymbol: 'ULAS.IS', marketCap: 0 },
  { symbol: 'ULUFA', name: 'Ulusal Faktoring', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'ULUFA.IS', marketCap: 0 },
  { symbol: 'UNLU', name: 'Ünlü Yatırım Holding', sector: 'Holding', basePrice: 10.00, yahooSymbol: 'UNLU.IS', marketCap: 0 },
  { symbol: 'VAKFA', name: 'Vakıf Faktoring', sector: 'Finans', basePrice: 10.00, yahooSymbol: 'VAKFA.IS', marketCap: 0 },
  { symbol: 'VKFYO', name: 'Vakıf Menkul Kıymet YO', sector: 'Yatırım', basePrice: 10.00, yahooSymbol: 'VKFYO.IS', marketCap: 0 },
  { symbol: 'VSNMD', name: 'Visne Madencilik', sector: 'Madencilik', basePrice: 10.00, yahooSymbol: 'VSNMD.IS', marketCap: 0 },
  { symbol: 'YIGIT', name: 'Yiğit Akü', sector: 'Otomotiv', basePrice: 10.00, yahooSymbol: 'YIGIT.IS', marketCap: 0 },
  { symbol: 'YONGA', name: 'Yonga Mobilya', sector: 'Mobilya', basePrice: 10.00, yahooSymbol: 'YONGA.IS', marketCap: 0 },
  { symbol: 'YYAPI', name: 'Yeşil Yapı Endüstrisi', sector: 'İnşaat', basePrice: 10.00, yahooSymbol: 'YYAPI.IS', marketCap: 0 },
  { symbol: 'Z30EA', name: 'Ziraat Portföy BIST 30 ETF A', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'Z30EA.IS', marketCap: 0 },
  { symbol: 'Z30KE', name: 'Ziraat Portföy BIST 30 ETF KE', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'Z30KE.IS', marketCap: 0 },
  { symbol: 'Z30KP', name: 'Ziraat Portföy BIST 30 ETF KP', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'Z30KP.IS', marketCap: 0 },
  { symbol: 'ZELOT', name: 'Ziraat Portföy BIST 50-30 ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ZELOT.IS', marketCap: 0 },
  { symbol: 'ZERGY', name: 'Zeray GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'ZERGY.IS', marketCap: 0 },
  { symbol: 'ZGOLD', name: 'Ziraat Portföy Altın ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ZGOLD.IS', marketCap: 0 },
  { symbol: 'ZGYO', name: 'Z GYO', sector: 'GYO', basePrice: 10.00, yahooSymbol: 'ZGYO.IS', marketCap: 0 },
  { symbol: 'ZPBDL', name: 'Ziraat Portföy BIST Banka Dışı ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ZPBDL.IS', marketCap: 0 },
  { symbol: 'ZPLIB', name: 'Ziraat Portföy BIST Likit Banka ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ZPLIB.IS', marketCap: 0 },
  { symbol: 'ZTLRF', name: 'Ziraat Portföy TLREF ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ZTLRF.IS', marketCap: 0 },
  { symbol: 'ZTLRK', name: 'Ziraat Portföy TLREF Katılım ETF', sector: 'Yatırım Fonu', basePrice: 10.00, yahooSymbol: 'ZTLRK.IS', marketCap: 0 },]

async function main() {
  console.log(`Seeding database with ${stocks.length} BIST 500 stocks...`)

  // Seed test user
  const hashedPassword = await bcrypt.hash('johndoe123', 12)
  await prisma.user.upsert({
    where: { email: 'john@doe.com' },
    update: { password: hashedPassword, role: 'admin' },
    create: {
      email: 'john@doe.com',
      name: 'John Doe',
      password: hashedPassword,
      role: 'admin',
      cashBalance: 100000,
    },
  })

  // Seed stocks
  for (const stock of stocks) {
    const variation = (Math.random() - 0.5) * stock.basePrice * 0.03
    const currentPrice = parseFloat((stock.basePrice + variation).toFixed(2))
    const previousClose = parseFloat((stock.basePrice + (Math.random() - 0.5) * stock.basePrice * 0.02).toFixed(2))
    const dayHigh = parseFloat((Math.max(currentPrice, previousClose) * (1 + Math.random() * 0.015)).toFixed(2))
    const dayLow = parseFloat((Math.min(currentPrice, previousClose) * (1 - Math.random() * 0.015)).toFixed(2))
    const volume = Math.floor(Math.random() * 50000000) + 5000000

    await prisma.stock.upsert({
      where: { symbol: stock.symbol },
      update: {
        name: stock.name,
        sector: stock.sector,
        exchange: 'BIST',
        currentPrice,
        previousClose,
        dayHigh,
        dayLow,
        volume,
        yahooSymbol: stock.yahooSymbol,
        marketCap: stock.marketCap,
      },
      create: {
        symbol: stock.symbol,
        name: stock.name,
        sector: stock.sector,
        exchange: 'BIST',
        basePrice: stock.basePrice,
        currentPrice,
        previousClose,
        dayHigh,
        dayLow,
        volume,
        marketCap: stock.marketCap,
        yahooSymbol: stock.yahooSymbol,
      },
    })
  }

  // Generate price history for new stocks (skip if already has data)
  const stocksInDb = await prisma.stock.findMany()
  for (const stock of stocksInDb) {
    const existingHistory = await prisma.priceHistory.count({ where: { stockId: stock.id } })
    if (existingHistory > 100) continue

    let price = stock.basePrice * 0.85
    const historyData = []
    const now = new Date()
    
    for (let i = 365; i >= 0; i--) {
      const date = new Date(now)
      date.setDate(date.getDate() - i)
      date.setHours(18, 0, 0, 0)
      
      const change = (Math.random() - 0.48) * price * 0.025
      price = Math.max(price * 0.5, price + change)
      
      const open = parseFloat((price * (1 + (Math.random() - 0.5) * 0.01)).toFixed(2))
      const close = parseFloat(price.toFixed(2))
      const high = parseFloat((Math.max(open, close) * (1 + Math.random() * 0.012)).toFixed(2))
      const low = parseFloat((Math.min(open, close) * (1 - Math.random() * 0.012)).toFixed(2))
      const vol = Math.floor(Math.random() * 30000000) + 5000000

      historyData.push({
        stockId: stock.id,
        price: close,
        open,
        high,
        low,
        close,
        volume: vol,
        timestamp: date,
      })
    }

    await prisma.priceHistory.createMany({ data: historyData })
  }

  // Deactivate delisted/renamed stocks
  const delistedSymbols: string[] = []
  for (const sym of delistedSymbols) {
    await prisma.stock.updateMany({ where: { symbol: sym }, data: { isActive: false } })
  }

  console.log(`Seeding completed! ${stocks.length} stocks added. ${delistedSymbols.length} deactivated.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
